# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Categoryモデル
## 親カテゴリー
category = Category.create(name: 'すべて')
ladys = category.children.create(name: 'レディース')
mens = category.children.create(name: 'メンズ')
babys = category.children.create(name: 'ベビー・キッズ')
interia = category.children.create(name: 'インテリア・住まい・小物')
books = category.children.create(name: '本・音楽・ゲーム')
hobby = category.children.create(name: 'おもちゃ・ホビー・グッズ')
cosme = category.children.create(name: 'コスメ・香水・美容')
cameras = category.children.create(name: '家電・スマホ・カメラ')
sport = category.children.create(name: 'スポーツ・レジャー')
hands = category.children.create(name: 'ハンドメイド')
tickets = category.children.create(name: 'チケット')
cars = category.children.create(name: '自動車・オートバイ')
others = category.children.create(name: 'その他')

## 子カテゴリー
### レディース
ladys_tops = ladys.children.create(name: 'トップス')
ladys_jaket = ladys.children.create(name: 'ジャケット/アウター')
ladys_pant = ladys.children.create(name: 'パンツ')
ladys_skirt = ladys.children.create(name: 'スカート')
ladys_wanpi = ladys.children.create(name: 'ワンピース')
ladys_shoes = ladys.children.create(name: '靴')
ladys_room = ladys.children.create(name: 'ルームウェア/パジャマ')
ladys_leg = ladys.children.create(name: 'レッグウェア')
ladys_hat = ladys.children.create(name: '帽子')
ladys_bag = ladys.children.create(name: 'バッグ')
ladys_accessary = ladys.children.create(name: 'アクセサリー')
ladys_hair = ladys.children.create(name: 'ヘアアクセサリー')
ladys_komono = ladys.children.create(name: '小物')
ladys_clock = ladys.children.create(name: '時計')
ladys_wig = ladys.children.create(name: 'ウィッグ/エクステ')
ladys_yukata = ladys.children.create(name: '浴衣/水着')
ladys_suutu = ladys.children.create(name: 'スーツ/フォーマル/ドレス')
ladys_matanity = ladys.children.create(name: 'マタニティ')
ladys_others = ladys.children.create(name: 'その他')
### メンズ
mens_tops = mens.children.create(name: 'トップス')
mens_jaket = mens.children.create(name: 'ジャケット/アウター')
mens_pant = mens.children.create(name: 'パンツ')
mens_shoes = mens.children.create(name: '靴')
mens_bag = mens.children.create(name: 'バッグ')
mens_suutu = mens.children.create(name: 'スーツ')
mens_hat = mens.children.create(name: '帽子')
mens_accessary = mens.children.create(name: 'アクセサリー')
mens_komono = mens.children.create(name: '小物')
mens_clock = mens.children.create(name: '時計')
mens_mizugi = mens.children.create(name: '水着')
mens_leg = mens.children.create(name: 'レッグウェア')
mens_under = mens.children.create(name: 'アンダーウェア')
mens_others = mens.children.create(name: 'その他')
### ベビー・キッズ
babys_girl95 = babys.children.create(name: 'ベビー服(女の子用) ~95cm')
babys_boy95 = babys.children.create(name: 'ベビー服(男の子用) ~95cm')
babys_both95 = babys.children.create(name: 'ベビー服(男女兼用) ~95cm')
babys_girl100 = babys.children.create(name: 'キッズ服(女の子用) 100cm~')
babys_boy100 = babys.children.create(name: 'キッズ服(男の子用) 100cm~')
babys_both100 = babys.children.create(name: 'キッズ服(男女兼用) 100cm~')
babys_shoes = babys.children.create(name: 'キッズ靴')
babys_fashion = babys.children.create(name: '子ども用ファッション小物')
babys_omutsu = babys.children.create(name: 'おむつ/トイレ/バス')
babys_move = babys.children.create(name: '外出/移動用具')
babys_lunch = babys.children.create(name: '授乳/食事')
babys_kagu = babys.children.create(name: 'ベビー家具/寝具/室内用品')
babys_toy = babys.children.create(name: 'おもちゃ')
babys_event = babys.children.create(name: '行事/記念品')
babys_others = babys.children.create(name: 'その他')
### インテリア
interia_kitchen = interia.children.create(name: 'キッチン/食器')
interia_bed = interia.children.create(name: 'ベッド/マットレス')
interia_sofa = interia.children.create(name: 'ソファ/ソファベッド')
interia_chair = interia.children.create(name: '椅子/チェア')
interia_desk = interia.children.create(name: '机/テーブル')
interia_kagu = interia.children.create(name: '収納家具')
interia_carpet = interia.children.create(name: 'ラグ/カーペット/マット')
interia_kirten = interia.children.create(name: 'カーテン/ブラインド')
interia_light = interia.children.create(name: 'ライト/照明')
interia_singu = interia.children.create(name: '寝具')
interia_komono = interia.children.create(name: 'インテリア小物')
interia_season = interia.children.create(name: '季節/年中行事')
interia_others = interia.children.create(name: 'その他')
### 本
books_book = books.children.create(name: '本')
books_manga = books.children.create(name: '漫画')
books_magazine = books.children.create(name: '雑誌')
books_cd = books.children.create(name: 'CD')
books_dvd = books.children.create(name: 'DVD/ブルーレイ')
books_record = books.children.create(name: 'レコード')
books_game = books.children.create(name: 'テレビゲーム')
### おもちゃ
hobby_toy = hobby.children.create(name: 'おもちゃ')
hobby_talent = hobby.children.create(name: 'タレントグッズ')
hobby_comic = hobby.children.create(name: 'コミック/アニメグッズ')
hobby_card = hobby.children.create(name: 'トレーディングカード')
hobby_figma = hobby.children.create(name: 'フィギュア')
hobby_gakki = hobby.children.create(name: '楽器/器材')
hobby_collection = hobby.children.create(name: 'コレクション')
hobby_military = hobby.children.create(name: 'ミリタリー')
hobby_art = hobby.children.create(name: '美術品')
hobby_arting = hobby.children.create(name: 'アート用品')
hobby_others = hobby.children.create(name: 'その他')
### コスメ
cosme_base = cosme.children.create(name: 'ベースメイク')
cosme_makeup = cosme.children.create(name: 'メイクアップ')
cosme_nail = cosme.children.create(name: 'ネイルケア')
cosme_kosui = cosme.children.create(name: '香水')
cosme_skin = cosme.children.create(name: 'スキンケア/基礎化粧品')
cosme_hair = cosme.children.create(name: 'ヘアケア')
cosme_body = cosme.children.create(name: 'ボディケア')
cosme_oral = cosme.children.create(name: 'オーラルケア')
cosme_relax = cosme.children.create(name: 'リラクゼーション')
cosme_diet = cosme.children.create(name: 'ダイエット')
cosme_others = cosme.children.create(name: 'その他')
### 家電・スマホ・カメラ
cameras_phone = cameras.children.create(name: 'スマートフォン/携帯電話')
cameras_phoneAccessary = cameras.children.create(name: 'スマホアクセサリー')
cameras_pc = cameras.children.create(name: 'PC/タブレット')
cameras_camera = cameras.children.create(name: 'カメラ')
cameras_televi = cameras.children.create(name: 'テレビ/映像機器')
cameras_audio = cameras.children.create(name: 'オーディオ機器')
cameras_biyou = cameras.children.create(name: '美容/健康')
cameras_reibou = cameras.children.create(name: '冷暖房/空調')
cameras_kaden = cameras.children.create(name: '生活家電')
cameras_others = cameras.children.create(name: 'その他')
### スポーツ・レジャー
sport_golf = sport.children.create(name: 'ゴルフ')
sport_fishing = sport.children.create(name: 'フィッシング')
sport_bike = sport.children.create(name: '自転車')
sport_training = sport.children.create(name: 'トレーニング/エクササイズ')
sport_baseball = sport.children.create(name: '野球')
sport_soccer = sport.children.create(name: 'サッカー/フットサル')
sport_tennis = sport.children.create(name: 'テニス')
sport_snow = sport.children.create(name: 'スノーボード')
sport_skii = sport.children.create(name: 'スキー')
sport_otherSports = sport.children.create(name: 'その他スポーツ')
sport_outdoor = sport.children.create(name: 'アウトドア')
sport_others = sport.children.create(name: 'その他')
### ハンドメイド
hands_accessary = hands.children.create(name: 'アクセサリー(女性用)')
hands_fashion = hands.children.create(name: 'ファッション/小物')
hands_clock = hands.children.create(name: 'アクセサリー/時計')
hands_interia = hands.children.create(name: '日用品/インテリア')
hands_hobby = hands.children.create(name: '趣味/おもちゃ')
hands_kids = hands.children.create(name: 'キッズ/ベビー')
hands_material = hands.children.create(name: '素材/材料')
hands_dojin = hands.children.create(name: '二次創作物')
hands_others = hands.children.create(name: 'その他')
### チケット
tickets_music = tickets.children.create(name: '音楽')
tickets_sports = tickets.children.create(name: 'スポーツ')
tickets_engeki = tickets.children.create(name: '演劇/芸能')
tickets_event = tickets.children.create(name: 'イベント')
tickets_movie = tickets.children.create(name: '映画')
tickets_shisetu = tickets.children.create(name: '施設利用券')
tickets_yuutai = tickets.children.create(name: '優待券/割引券')
tickets_others = tickets.children.create(name: 'その他')
### 自転車・オートバイ
cars_bike = cars.children.create(name: '自動車本体')
cars_hoile = cars.children.create(name: '自動車タイヤ/ホイール')
cars_wheel = cars.children.create(name: '自動車パーツ')
cars_accessary = cars.children.create(name: '自動車アクセサリー')
cars_autobike = cars.children.create(name: 'オートバイ車体')
cars_parts = cars.children.create(name: 'オートバイパーツ')
cars_autobikeAccessary = cars.children.create(name: 'オートバイアクセサリー')
### その他
others_matome = others.children.create(name: 'まとめ売り')
others_pet = others.children.create(name: 'ペット用品')
others_foods = others.children.create(name: '食品')
others_sake = others.children.create(name: '食料/酒')
others_zakka = others.children.create(name: '日用品/生活雑貨/旅行')
others_antike = others.children.create(name: 'アンティーク/コレクション')
others_bunbogu = others.children.create(name: '文房具/事務用品')
others_jimu = others.children.create(name: '事務/店舗用品')
others_others = others.children.create(name: 'その他')

### 孫カテゴリー
#### レディース-トップス
ladys_tops_grand = ladys_tops.children.create(name: 'Tシャツ/カットソー(半袖/袖なし)')
ladys_tops_grand = ladys_tops.children.create(name: 'Tシャツ/カットソー(七分/長袖)')
ladys_tops_grand = ladys_tops.children.create(name: 'シャツ/ブラウス(半袖/袖なし)')
ladys_tops_grand = ladys_tops.children.create(name: 'シャツ/ブラウス(七分/長袖)')
ladys_tops_grand = ladys_tops.children.create(name: 'ポロシャツ')
ladys_tops_grand = ladys_tops.children.create(name: 'キャミソール')
ladys_tops_grand = ladys_tops.children.create(name: 'タンクトップ')
ladys_tops_grand = ladys_tops.children.create(name: 'ホルターネック')
ladys_tops_grand = ladys_tops.children.create(name: 'ニット/セーター')
ladys_tops_grand = ladys_tops.children.create(name: 'チュニック')
ladys_tops_grand = ladys_tops.children.create(name: 'カーディガン/ボレロ')
ladys_tops_grand = ladys_tops.children.create(name: 'アンサンブル')
ladys_tops_grand = ladys_tops.children.create(name: 'ベスト/ジレ')
ladys_tops_grand = ladys_tops.children.create(name: 'パーカー')
ladys_tops_grand = ladys_tops.children.create(name: 'トレーナー/スウェット')
ladys_tops_grand = ladys_tops.children.create(name: 'ベアトップ/チューブトップ')
ladys_tops_grand = ladys_tops.children.create(name: 'ジャージ')
ladys_tops_grand = ladys_tops.children.create(name: 'その他')
#### レディース-ジャケット/アウター
ladys_jaket_grand = ladys_jaket.children.create(name: 'テーラードジャケット')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ノーカラージャケット')
ladys_jaket_grand = ladys_jaket.children.create(name: 'Gジャン/デニムジャケット')
ladys_jaket_grand = ladys_jaket.children.create(name: 'レザージャケット')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ダウンジャケット')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ライダースジャケット')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ミリタリージャケット')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ダウンベスト')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ジャンパー/ブルゾン')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ポンチョ')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ロングコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'トレンチコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ダッフルコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'ピーコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'チェスターコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'モッズコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'スタジャン')
ladys_jaket_grand = ladys_jaket.children.create(name: '毛皮/ファーコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'スプリングコート')
ladys_jaket_grand = ladys_jaket.children.create(name: 'スカジャン')
ladys_jaket_grand = ladys_jaket.children.create(name: 'その他')
#### レディース-パンツ
ladys_pant_grand = ladys_pant.children.create(name: 'デニム/ジーンズ')
ladys_pant_grand = ladys_pant.children.create(name: 'ショートパンツ')
ladys_pant_grand = ladys_pant.children.create(name: 'カジュアルパンツ')
ladys_pant_grand = ladys_pant.children.create(name: 'ハーフパンツ')
ladys_pant_grand = ladys_pant.children.create(name: 'チノパン')
ladys_pant_grand = ladys_pant.children.create(name: 'ワークパンツ/カーゴパンツ')
ladys_pant_grand = ladys_pant.children.create(name: 'クロップドパンツ')
ladys_pant_grand = ladys_pant.children.create(name: 'サロペット/オーバーオール')
ladys_pant_grand = ladys_pant.children.create(name: 'オールインワン')
ladys_pant_grand = ladys_pant.children.create(name: 'サルエルパンツ')
ladys_pant_grand = ladys_pant.children.create(name: 'ガウチョパンツ')
ladys_pant_grand = ladys_pant.children.create(name: 'その他')
#### レディース-スカート
ladys_skirt_grand = ladys_skirt.children.create(name: 'ミニスカート')
ladys_skirt_grand = ladys_skirt.children.create(name: 'ひざ丈スカート')
ladys_skirt_grand = ladys_skirt.children.create(name: 'ロングスカート')
ladys_skirt_grand = ladys_skirt.children.create(name: 'キュロット')
ladys_skirt_grand = ladys_skirt.children.create(name: 'その他')
#### レディース-ワンピース
ladys_wanpi_grand = ladys_wanpi.children.create(name: 'ミニワンピース')
ladys_wanpi_grand = ladys_wanpi.children.create(name: 'ひざ丈ワンピース')
ladys_wanpi_grand = ladys_wanpi.children.create(name: 'ロングワンピース')
ladys_wanpi_grand = ladys_wanpi.children.create(name: 'その他')
#### レディース-靴
ladys_shoes_grand = ladys_shoes.children.create(name: 'ハイヒール/パンプス')
ladys_shoes_grand = ladys_shoes.children.create(name: 'ブーツ')
ladys_shoes_grand = ladys_shoes.children.create(name: 'サンダル')
ladys_shoes_grand = ladys_shoes.children.create(name: 'スニーカー')
ladys_shoes_grand = ladys_shoes.children.create(name: 'ミュール')
ladys_shoes_grand = ladys_shoes.children.create(name: 'モカシン')
ladys_shoes_grand = ladys_shoes.children.create(name: 'ローファー/革靴')
ladys_shoes_grand = ladys_shoes.children.create(name: 'フラットシューズ/バレエシューズ')
ladys_shoes_grand = ladys_shoes.children.create(name: '長靴/レインシューズ')
ladys_shoes_grand = ladys_shoes.children.create(name: 'その他')
#### レディース-ルームウェア/パジャマ
ladys_room_grand = ladys_room.children.create(name: 'パジャマ')
ladys_room_grand = ladys_room.children.create(name: 'ルームウェア')
#### レディース-レッグウェア
ladys_leg_grand = ladys_leg.children.create(name: 'ソックス')
ladys_leg_grand = ladys_leg.children.create(name: 'スパッツ/レギンス')
ladys_leg_grand = ladys_leg.children.create(name: 'ストッキング/タイツ')
ladys_leg_grand = ladys_leg.children.create(name: 'レッグウォーマー')
ladys_leg_grand = ladys_leg.children.create(name: 'その他')
#### レディース-帽子
ladys_hat_grand = ladys_hat.children.create(name: 'ニットキャップ/ビーニー')
ladys_hat_grand = ladys_hat.children.create(name: 'ハット')
ladys_hat_grand = ladys_hat.children.create(name: 'ハンチング/ベレー帽')
ladys_hat_grand = ladys_hat.children.create(name: 'キャップ')
ladys_hat_grand = ladys_hat.children.create(name: 'キャスケット')
ladys_hat_grand = ladys_hat.children.create(name: '麦わら帽子')
ladys_hat_grand = ladys_hat.children.create(name: 'その他')
#### レディース-バッグ
ladys_bag_grand = ladys_bag.children.create(name: 'ハンドバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'トートバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'エコバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'リュック/バックパック')
ladys_bag_grand = ladys_bag.children.create(name: 'ボストンバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'スポーツバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'ショルダーバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'クラッチバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'ポーチ/バニティ')
ladys_bag_grand = ladys_bag.children.create(name: 'ボディバッグ/ウェストバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'マザーズバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'メッセンジャーバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'ビジネスバッグ')
ladys_bag_grand = ladys_bag.children.create(name: '旅行用バッグ/キャリーバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'ショップ袋')
ladys_bag_grand = ladys_bag.children.create(name: '和装用バッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'かごバッグ')
ladys_bag_grand = ladys_bag.children.create(name: 'その他')
#### レディース-アクセサリー
ladys_accessary_grand = ladys_accessary.children.create(name: 'ネックレス')
ladys_accessary_grand = ladys_accessary.children.create(name: 'ブレスレット')
ladys_accessary_grand = ladys_accessary.children.create(name: 'バングル/リストバンド')
ladys_accessary_grand = ladys_accessary.children.create(name: 'リング')
ladys_accessary_grand = ladys_accessary.children.create(name: 'ピアス(片耳用)')
ladys_accessary_grand = ladys_accessary.children.create(name: 'ピアス(両耳用)')
ladys_accessary_grand = ladys_accessary.children.create(name: 'イヤリング')
ladys_accessary_grand = ladys_accessary.children.create(name: 'アンクレット')
ladys_accessary_grand = ladys_accessary.children.create(name: 'ブローチ/コサージュ')
ladys_accessary_grand = ladys_accessary.children.create(name: 'チャーム')
ladys_accessary_grand = ladys_accessary.children.create(name: 'その他')
#### レディース-ヘアアクセサリー
ladys_hair_grand = ladys_hair.children.create(name: 'ヘアゴム/シュシュ')
ladys_hair_grand = ladys_hair.children.create(name: 'ヘアバンド/カチューシャ')
ladys_hair_grand = ladys_hair.children.create(name: 'ヘアピン')
ladys_hair_grand = ladys_hair.children.create(name: 'その他')
#### レディース-小物
ladys_komono_grand = ladys_komono.children.create(name: '長財布')
ladys_komono_grand = ladys_komono.children.create(name: '折り財布')
ladys_komono_grand = ladys_komono.children.create(name: 'コインケース/小銭入れ')
ladys_komono_grand = ladys_komono.children.create(name: '名刺入れ/定期入れ')
ladys_komono_grand = ladys_komono.children.create(name: 'キーケース')
ladys_komono_grand = ladys_komono.children.create(name: 'キーホルダー')
ladys_komono_grand = ladys_komono.children.create(name: '手袋/アームカバー')
ladys_komono_grand = ladys_komono.children.create(name: 'ハンカチ')
ladys_komono_grand = ladys_komono.children.create(name: 'ベルト')
ladys_komono_grand = ladys_komono.children.create(name: 'マフラー/ショール')
ladys_komono_grand = ladys_komono.children.create(name: 'ストール/スヌード')
ladys_komono_grand = ladys_komono.children.create(name: 'バンダナ/スカーフ')
ladys_komono_grand = ladys_komono.children.create(name: 'ネックウォーマー')
ladys_komono_grand = ladys_komono.children.create(name: 'サスペンダー')
ladys_komono_grand = ladys_komono.children.create(name: 'サングラス/メガネ')
ladys_komono_grand = ladys_komono.children.create(name: 'モバイルケース/カバー')
ladys_komono_grand = ladys_komono.children.create(name: '手帳')
ladys_komono_grand = ladys_komono.children.create(name: 'イヤマフラー')
ladys_komono_grand = ladys_komono.children.create(name: '傘')
ladys_komono_grand = ladys_komono.children.create(name: 'レインコート/ポンチョ')
ladys_komono_grand = ladys_komono.children.create(name: 'ミラー')
ladys_komono_grand = ladys_komono.children.create(name: 'タバコグッズ')
ladys_komono_grand = ladys_komono.children.create(name: 'その他')
#### レディース-時計
ladys_clock_grand = ladys_clock.children.create(name: '腕時計(アナログ)')
ladys_clock_grand = ladys_clock.children.create(name: '腕時計(デジタル)')
ladys_clock_grand = ladys_clock.children.create(name: 'ラバーベルト')
ladys_clock_grand = ladys_clock.children.create(name: 'レザーベルト')
ladys_clock_grand = ladys_clock.children.create(name: '金属ベルト')
ladys_clock_grand = ladys_clock.children.create(name: 'その他')
#### レディース-ウィッグ/エクステ
ladys_wig_grand = ladys_wig.children.create(name: '前髪ウィッグ')
ladys_wig_grand = ladys_wig.children.create(name: 'ロングストレート')
ladys_wig_grand = ladys_wig.children.create(name: 'ロングカール')
ladys_wig_grand = ladys_wig.children.create(name: 'ショートストレート')
ladys_wig_grand = ladys_wig.children.create(name: 'ショートカール')
ladys_wig_grand = ladys_wig.children.create(name: 'その他')
#### レディース-浴衣/水着
ladys_yukata_grand = ladys_yukata.children.create(name: '浴衣')
ladys_yukata_grand = ladys_yukata.children.create(name: '着物')
ladys_yukata_grand = ladys_yukata.children.create(name: '振袖')
ladys_yukata_grand = ladys_yukata.children.create(name: '長襦袢/半襦袢')
ladys_yukata_grand = ladys_yukata.children.create(name: '水着セパレート')
ladys_yukata_grand = ladys_yukata.children.create(name: '水着ワンピース')
ladys_yukata_grand = ladys_yukata.children.create(name: '水着スポーツ用')
ladys_yukata_grand = ladys_yukata.children.create(name: 'その他')
#### レディース-スーツ/フォーマル/ドレス
ladys_suutu_grand = ladys_suutu.children.create(name: 'スカートスーツ上下')
ladys_suutu_grand = ladys_suutu.children.create(name: 'パンツスーツ上下')
ladys_suutu_grand = ladys_suutu.children.create(name: 'ドレス')
ladys_suutu_grand = ladys_suutu.children.create(name: 'パーティーバッグ')
ladys_suutu_grand = ladys_suutu.children.create(name: 'シューズ')
ladys_suutu_grand = ladys_suutu.children.create(name: 'ウェディング')
ladys_suutu_grand = ladys_suutu.children.create(name: 'その他')
#### レディース-マタニティ
ladys_matanity_grand = ladys_matanity.children.create(name: 'トップス')
ladys_matanity_grand = ladys_matanity.children.create(name: 'アウター')
ladys_matanity_grand = ladys_matanity.children.create(name: 'インナー')
ladys_matanity_grand = ladys_matanity.children.create(name: 'ワンピース')
ladys_matanity_grand = ladys_matanity.children.create(name: 'パンツ/スパッツ')
ladys_matanity_grand = ladys_matanity.children.create(name: 'スカート')
ladys_matanity_grand = ladys_matanity.children.create(name: 'パジャマ')
ladys_matanity_grand = ladys_matanity.children.create(name: '授乳服')
ladys_matanity_grand = ladys_matanity.children.create(name: 'その他')
#### レディース-その他
ladys_others_grand = ladys_others.children.create(name: 'コスプレ')
ladys_others_grand = ladys_others.children.create(name: '下着')
ladys_others_grand = ladys_others.children.create(name: 'その他')
#### メンズ-トップス
mens_tops_grand = mens_tops.children.create(name: 'Tシャツ/カットソー(半袖/袖なし)')
mens_tops_grand = mens_tops.children.create(name: 'Tシャツ/カットソー(七分/長袖)')
mens_tops_grand = mens_tops.children.create(name: 'シャツ')
mens_tops_grand = mens_tops.children.create(name: 'ポロシャツ')
mens_tops_grand = mens_tops.children.create(name: 'タンクトップ')
mens_tops_grand = mens_tops.children.create(name: 'ニット/セーター')
mens_tops_grand = mens_tops.children.create(name: 'パーカー')
mens_tops_grand = mens_tops.children.create(name: 'カーディガン')
mens_tops_grand = mens_tops.children.create(name: 'スウェット')
mens_tops_grand = mens_tops.children.create(name: 'ジャージ')
mens_tops_grand = mens_tops.children.create(name: 'ベスト')
mens_tops_grand = mens_tops.children.create(name: 'その他')
#### メンズ-ジャケット/アウター
mens_jaket_grand = mens_jaket.children.create(name: 'テーラードジャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'ノーカラージャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'Gジャン/デニムジャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'レザージャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'ダウンジャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'ライダースジャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'ミリタリージャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'ナイロンジャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'フライトジャケット')
mens_jaket_grand = mens_jaket.children.create(name: 'ダッフルコート')
mens_jaket_grand = mens_jaket.children.create(name: 'ピーコート')
mens_jaket_grand = mens_jaket.children.create(name: 'ステンカラーコート')
mens_jaket_grand = mens_jaket.children.create(name: 'トレンチコート')
mens_jaket_grand = mens_jaket.children.create(name: 'モッズコート')
mens_jaket_grand = mens_jaket.children.create(name: 'チェスターコート')
mens_jaket_grand = mens_jaket.children.create(name: 'スタジャン')
mens_jaket_grand = mens_jaket.children.create(name: 'スカジャン')
mens_jaket_grand = mens_jaket.children.create(name: 'ブルゾン')
mens_jaket_grand = mens_jaket.children.create(name: 'マウンテンパーカー')
mens_jaket_grand = mens_jaket.children.create(name: 'ダウンベスト')
mens_jaket_grand = mens_jaket.children.create(name: 'ポンチョ')
mens_jaket_grand = mens_jaket.children.create(name: 'カバーオール')
mens_jaket_grand = mens_jaket.children.create(name: 'その他')
#### メンズ-パンツ
mens_pant_grand = mens_pant.children.create(name: 'デニム/ジーンズ')
mens_pant_grand = mens_pant.children.create(name: 'ワークパンツ/カーゴパンツ')
mens_pant_grand = mens_pant.children.create(name: 'スラックス')
mens_pant_grand = mens_pant.children.create(name: 'チノパン')
mens_pant_grand = mens_pant.children.create(name: 'ショートパンツ')
mens_pant_grand = mens_pant.children.create(name: 'ペインターパンツ')
mens_pant_grand = mens_pant.children.create(name: 'サルエルパンツ')
mens_pant_grand = mens_pant.children.create(name: 'オーバーオール')
mens_pant_grand = mens_pant.children.create(name: 'その他')
#### メンズ-靴
mens_shoes_grand = mens_shoes.children.create(name: 'スニーカー')
mens_shoes_grand = mens_shoes.children.create(name: 'サンダル')
mens_shoes_grand = mens_shoes.children.create(name: 'ブーツ')
mens_shoes_grand = mens_shoes.children.create(name: 'モカシン')
mens_shoes_grand = mens_shoes.children.create(name: 'ドレス/ビジネス')
mens_shoes_grand = mens_shoes.children.create(name: '長靴/レインシューズ')
mens_shoes_grand = mens_shoes.children.create(name: 'デッキシューズ')
mens_shoes_grand = mens_shoes.children.create(name: 'その他')
#### メンズ-バッグ
mens_bag_grand = mens_bag.children.create(name: 'ショルダーバッグ')
mens_bag_grand = mens_bag.children.create(name: 'トートバッグ')
mens_bag_grand = mens_bag.children.create(name: 'ボストンバッグ')
mens_bag_grand = mens_bag.children.create(name: 'リュック/バックパック')
mens_bag_grand = mens_bag.children.create(name: 'ウエストポーチ')
mens_bag_grand = mens_bag.children.create(name: 'ボディーバッグ')
mens_bag_grand = mens_bag.children.create(name: 'ドラムバッグ')
mens_bag_grand = mens_bag.children.create(name: 'ビジネスバッグ')
mens_bag_grand = mens_bag.children.create(name: 'トラベルバッグ')
mens_bag_grand = mens_bag.children.create(name: 'メッセンジャーバッグ')
mens_bag_grand = mens_bag.children.create(name: 'エコバッグ')
mens_bag_grand = mens_bag.children.create(name: 'その他')
#### メンズ-スーツ
mens_suutu_grand = mens_suutu.children.create(name: 'スーツジャケット')
mens_suutu_grand = mens_suutu.children.create(name: 'スーツベスト')
mens_suutu_grand = mens_suutu.children.create(name: 'スラックス')
mens_suutu_grand = mens_suutu.children.create(name: 'セットアップ')
mens_suutu_grand = mens_suutu.children.create(name: 'その他')
#### メンズ-帽子
mens_hat_grand = mens_hat.children.create(name: 'キャップ')
mens_hat_grand = mens_hat.children.create(name: 'ハット')
mens_hat_grand = mens_hat.children.create(name: 'ニットキャップ/ビーニー')
mens_hat_grand = mens_hat.children.create(name: 'ハンチング/ベレー帽')
mens_hat_grand = mens_hat.children.create(name: 'キャスケット')
mens_hat_grand = mens_hat.children.create(name: 'サンバイザー')
mens_hat_grand = mens_hat.children.create(name: 'その他')
#### メンズ-アクセサリー
mens_accessary_grand = mens_accessary.children.create(name: 'ネックレス')
mens_accessary_grand = mens_accessary.children.create(name: 'ブレスレット')
mens_accessary_grand = mens_accessary.children.create(name: 'バングル/リストバンド')
mens_accessary_grand = mens_accessary.children.create(name: 'リング')
mens_accessary_grand = mens_accessary.children.create(name: 'ピアス(片耳用)')
mens_accessary_grand = mens_accessary.children.create(name: 'ピアス(両耳用)')
mens_accessary_grand = mens_accessary.children.create(name: 'アンクレット')
mens_accessary_grand = mens_accessary.children.create(name: 'その他')
#### メンズ-小物
mens_komono_grand = mens_komono.children.create(name: '長財布')
mens_komono_grand = mens_komono.children.create(name: '折り財布')
mens_komono_grand = mens_komono.children.create(name: 'マネークリップ')
mens_komono_grand = mens_komono.children.create(name: 'コインケース/小銭入れ')
mens_komono_grand = mens_komono.children.create(name: '名刺入れ/定期入れ')
mens_komono_grand = mens_komono.children.create(name: 'キーケース')
mens_komono_grand = mens_komono.children.create(name: 'キーホルダー')
mens_komono_grand = mens_komono.children.create(name: 'ネクタイ')
mens_komono_grand = mens_komono.children.create(name: '手袋')
mens_komono_grand = mens_komono.children.create(name: 'ハンカチ')
mens_komono_grand = mens_komono.children.create(name: 'ベルト')
mens_komono_grand = mens_komono.children.create(name: 'マフラー')
mens_komono_grand = mens_komono.children.create(name: 'ストール')
mens_komono_grand = mens_komono.children.create(name: 'バンダナ')
mens_komono_grand = mens_komono.children.create(name: 'ネックウォーマー')
mens_komono_grand = mens_komono.children.create(name: 'サスペンダー')
mens_komono_grand = mens_komono.children.create(name: 'ウォレットチェーン')
mens_komono_grand = mens_komono.children.create(name: 'サングラス/メガネ')
mens_komono_grand = mens_komono.children.create(name: 'モバイルケース/カバー')
mens_komono_grand = mens_komono.children.create(name: '手帳')
mens_komono_grand = mens_komono.children.create(name: 'ストラップ')
mens_komono_grand = mens_komono.children.create(name: 'ネクタイピン')
mens_komono_grand = mens_komono.children.create(name: 'カフリンクス')
mens_komono_grand = mens_komono.children.create(name: 'イヤマフラー')
mens_komono_grand = mens_komono.children.create(name: '傘')
mens_komono_grand = mens_komono.children.create(name: 'レインコート')
mens_komono_grand = mens_komono.children.create(name: 'ミラー')
mens_komono_grand = mens_komono.children.create(name: 'タバコグッズ')
mens_komono_grand = mens_komono.children.create(name: 'その他')
#### メンズ-時計
mens_clock_grand = mens_clock.children.create(name: '腕時計(アナログ)')
mens_clock_grand = mens_clock.children.create(name: '腕時計(デジタル)')
mens_clock_grand = mens_clock.children.create(name: 'ラバーベルト')
mens_clock_grand = mens_clock.children.create(name: 'レザーベルト')
mens_clock_grand = mens_clock.children.create(name: '金属ベルト')
mens_clock_grand = mens_clock.children.create(name: 'その他')
#### メンズ-水着
mens_mizugi_grand = mens_mizugi.children.create(name: '一般水着')
mens_mizugi_grand = mens_mizugi.children.create(name: 'スポーツ用')
mens_mizugi_grand = mens_mizugi.children.create(name: 'アクセサリー')
mens_mizugi_grand = mens_mizugi.children.create(name: 'その他')
#### メンズ-レッグウェア
mens_leg_grand = mens_leg.children.create(name: 'ソックス')
mens_leg_grand = mens_leg.children.create(name: 'レギンス/スパッツ')
mens_leg_grand = mens_leg.children.create(name: 'レッグウォーマー')
mens_leg_grand = mens_leg.children.create(name: 'その他')
#### メンズ-アンダーウェア
mens_under_grand = mens_under.children.create(name: 'トランクス')
mens_under_grand = mens_under.children.create(name: 'ボクサーパンツ')
mens_under_grand = mens_under.children.create(name: 'その他')
#### メンズ-その他
#### ベビー・キッズ-ベビー服(女の子用) ~95cm
babys_girl95_grand = babys_girl95.children.create(name: 'トップス')
babys_girl95_grand = babys_girl95.children.create(name: 'アウター')
babys_girl95_grand = babys_girl95.children.create(name: 'パンツ')
babys_girl95_grand = babys_girl95.children.create(name: 'スカート')
babys_girl95_grand = babys_girl95.children.create(name: 'ワンピース')
babys_girl95_grand = babys_girl95.children.create(name: 'ベビードレス')
babys_girl95_grand = babys_girl95.children.create(name: 'おくるみ')
babys_girl95_grand = babys_girl95.children.create(name: '下着/肌着')
babys_girl95_grand = babys_girl95.children.create(name: 'パジャマ')
babys_girl95_grand = babys_girl95.children.create(name: 'ロンパース')
babys_girl95_grand = babys_girl95.children.create(name: 'その他')
#### ベビー・キッズ-ベビー服(男の子用) ~95cm
babys_boy95_grand = babys_boy95.children.create(name: 'トップス')
babys_boy95_grand = babys_boy95.children.create(name: 'アウター')
babys_boy95_grand = babys_boy95.children.create(name: 'パンツ')
babys_boy95_grand = babys_boy95.children.create(name: 'おくるみ')
babys_boy95_grand = babys_boy95.children.create(name: '下着/肌着')
babys_boy95_grand = babys_boy95.children.create(name: 'パジャマ')
babys_boy95_grand = babys_boy95.children.create(name: 'ロンパース')
babys_boy95_grand = babys_boy95.children.create(name: 'その他')
#### ベビー・キッズ-ベビー服(男女兼用) ~95cm
babys_both95_grand = babys_both95.children.create(name: 'トップス')
babys_both95_grand = babys_both95.children.create(name: 'アウター')
babys_both95_grand = babys_both95.children.create(name: 'パンツ')
babys_both95_grand = babys_both95.children.create(name: 'おくるみ')
babys_both95_grand = babys_both95.children.create(name: '下着/肌着')
babys_both95_grand = babys_both95.children.create(name: 'パジャマ')
babys_both95_grand = babys_both95.children.create(name: 'ロンパース')
babys_both95_grand = babys_both95.children.create(name: 'その他')
#### ベビー・キッズ-キッズ服(女の子用) 100cm~
babys_girl100_grand = babys_girl100.children.create(name: 'コート')
babys_girl100_grand = babys_girl100.children.create(name: 'ジャケット/上着')
babys_girl100_grand = babys_girl100.children.create(name: 'トップス(Tシャツ/カットソー)')
babys_girl100_grand = babys_girl100.children.create(name: 'トップス(トレーナー)')
babys_girl100_grand = babys_girl100.children.create(name: 'トップス(チュニック)')
babys_girl100_grand = babys_girl100.children.create(name: 'トップス(タンクトップ)')
babys_girl100_grand = babys_girl100.children.create(name: 'トップス(その他)')
babys_girl100_grand = babys_girl100.children.create(name: 'スカート')
babys_girl100_grand = babys_girl100.children.create(name: 'パンツ')
babys_girl100_grand = babys_girl100.children.create(name: 'ワンピース')
babys_girl100_grand = babys_girl100.children.create(name: 'セットアップ')
babys_girl100_grand = babys_girl100.children.create(name: 'パジャマ')
babys_girl100_grand = babys_girl100.children.create(name: 'フォーマル/ドレス')
babys_girl100_grand = babys_girl100.children.create(name: '和服')
babys_girl100_grand = babys_girl100.children.create(name: '浴衣')
babys_girl100_grand = babys_girl100.children.create(name: '甚平')
babys_girl100_grand = babys_girl100.children.create(name: '水着')
babys_girl100_grand = babys_girl100.children.create(name: 'その他')
#### ベビー・キッズ-キッズ服(男の子用) 100cm~
babys_boy100_grand = babys_boy100.children.create(name: 'コート')
babys_boy100_grand = babys_boy100.children.create(name: 'ジャケット/上着')
babys_boy100_grand = babys_boy100.children.create(name: 'トップス(Tシャツ/カットソー)')
babys_boy100_grand = babys_boy100.children.create(name: 'トップス(トレーナー)')
babys_boy100_grand = babys_boy100.children.create(name: 'トップス(その他)')
babys_boy100_grand = babys_boy100.children.create(name: 'パンツ')
babys_boy100_grand = babys_boy100.children.create(name: 'セットアップ')
babys_boy100_grand = babys_boy100.children.create(name: 'パジャマ')
babys_boy100_grand = babys_boy100.children.create(name: 'フォーマル/ドレス')
babys_boy100_grand = babys_boy100.children.create(name: '和服')
babys_boy100_grand = babys_boy100.children.create(name: '浴衣')
babys_boy100_grand = babys_boy100.children.create(name: '甚平')
babys_boy100_grand = babys_boy100.children.create(name: '水着')
babys_boy100_grand = babys_boy100.children.create(name: 'その他')
#### ベビー・キッズ-キッズ服(男女兼用) 100cm~
babys_both100_grand = babys_both100.children.create(name: 'コート')
babys_both100_grand = babys_both100.children.create(name: 'ジャケット/上着')
babys_both100_grand = babys_both100.children.create(name: 'トップス(Tシャツ/カットソー)')
babys_both100_grand = babys_both100.children.create(name: 'トップス(トレーナー)')
babys_both100_grand = babys_both100.children.create(name: 'トップス(その他)')
babys_both100_grand = babys_both100.children.create(name: 'ボトムス')
babys_both100_grand = babys_both100.children.create(name: 'パジャマ')
babys_both100_grand = babys_both100.children.create(name: 'その他')
#### ベビー・キッズ-キッズ靴
babys_shoes_grand = babys_shoes.children.create(name: 'スニーカー')
babys_shoes_grand = babys_shoes.children.create(name: 'サンダル')
babys_shoes_grand = babys_shoes.children.create(name: 'ブーツ')
babys_shoes_grand = babys_shoes.children.create(name: '長靴')
babys_shoes_grand = babys_shoes.children.create(name: 'その他')
#### ベビー・キッズ-子ども用ファッション小物
babys_fashion_grand = babys_fashion.children.create(name: '靴下/スパッツ')
babys_fashion_grand = babys_fashion.children.create(name: '帽子')
babys_fashion_grand = babys_fashion.children.create(name: 'エプロン')
babys_fashion_grand = babys_fashion.children.create(name: 'サスペンダー')
babys_fashion_grand = babys_fashion.children.create(name: 'タイツ')
babys_fashion_grand = babys_fashion.children.create(name: 'ハンカチ')
babys_fashion_grand = babys_fashion.children.create(name: 'バンダナ')
babys_fashion_grand = babys_fashion.children.create(name: 'ベルト')
babys_fashion_grand = babys_fashion.children.create(name: 'マフラー')
babys_fashion_grand = babys_fashion.children.create(name: '傘')
babys_fashion_grand = babys_fashion.children.create(name: '手袋')
babys_fashion_grand = babys_fashion.children.create(name: 'スタイ')
babys_fashion_grand = babys_fashion.children.create(name: 'バッグ')
babys_fashion_grand = babys_fashion.children.create(name: 'その他')
#### ベビー・キッズ-おむつ/トイレ/バス
babys_omutsu_grand = babys_omutsu.children.create(name: 'おむつ用品')
babys_omutsu_grand = babys_omutsu.children.create(name: 'おまる/補助便座')
babys_omutsu_grand = babys_omutsu.children.create(name: 'トレーニングパンツ')
babys_omutsu_grand = babys_omutsu.children.create(name: 'ベビーバス')
babys_omutsu_grand = babys_omutsu.children.create(name: 'お風呂用品')
babys_omutsu_grand = babys_omutsu.children.create(name: 'その他')
#### ベビー・キッズ-外出/移動用品
babys_move_grand = babys_move.children.create(name: 'ベビーカー')
babys_move_grand = babys_move.children.create(name: '抱っこひも/スリング')
babys_move_grand = babys_move.children.create(name: 'チャイルドシート')
babys_move_grand = babys_move.children.create(name: 'その他')
#### ベビー・キッズ-授乳/食事
babys_lunch_grand = babys_lunch.children.create(name: 'ミルク')
babys_lunch_grand = babys_lunch.children.create(name: 'ベビーフード')
babys_lunch_grand = babys_lunch.children.create(name: 'ベビー用食器')
babys_lunch_grand = babys_lunch.children.create(name: 'その他')
#### ベビー・キッズ-ベビー家具/寝具/室内用品
babys_kagu_grand = babys_kagu.children.create(name: 'ベッド')
babys_kagu_grand = babys_kagu.children.create(name: '布団/毛布')
babys_kagu_grand = babys_kagu.children.create(name: 'イス')
babys_kagu_grand = babys_kagu.children.create(name: 'たんす')
babys_kagu_grand = babys_kagu.children.create(name: 'その他')
#### ベビー・キッズ-おもちゃ
babys_toy_grand = babys_toy.children.create(name: 'おふろのおもちゃ')
babys_toy_grand = babys_toy.children.create(name: 'がらがら')
babys_toy_grand = babys_toy.children.create(name: 'オルゴール')
babys_toy_grand = babys_toy.children.create(name: 'ベビージム')
babys_toy_grand = babys_toy.children.create(name: '手押し車/カタカタ')
babys_toy_grand = babys_toy.children.create(name: '知育玩具')
babys_toy_grand = babys_toy.children.create(name: 'その他')
#### ベビー・キッズ-行事/記念品
babys_event_grand = babys_event.children.create(name: 'お宮参り用品')
babys_event_grand = babys_event.children.create(name: 'お食い初め用品')
babys_event_grand = babys_event.children.create(name: 'アルバム')
babys_event_grand = babys_event.children.create(name: '手形/足形')
babys_event_grand = babys_event.children.create(name: 'その他')
#### ベビー・キッズ-その他
babys_others_grand = babys_others.children.create(name: '母子手帳用品')
babys_others_grand = babys_others.children.create(name: 'その他')
#### インテリア・住まい・小物-キッチン/食器
interia_kitchen_grand = interia_kitchen.children.create(name: '食器')
interia_kitchen_grand = interia_kitchen.children.create(name: '調理器具')
interia_kitchen_grand = interia_kitchen.children.create(name: '収納/キッチン雑貨')
interia_kitchen_grand = interia_kitchen.children.create(name: '弁当用品')
interia_kitchen_grand = interia_kitchen.children.create(name: 'カトラリー(スプーン等)')
interia_kitchen_grand = interia_kitchen.children.create(name: 'テーブル用品')
interia_kitchen_grand = interia_kitchen.children.create(name: '容器')
interia_kitchen_grand = interia_kitchen.children.create(name: 'エプロン')
interia_kitchen_grand = interia_kitchen.children.create(name: 'アルコールグッズ')
interia_kitchen_grand = interia_kitchen.children.create(name: '浄水機')
interia_kitchen_grand = interia_kitchen.children.create(name: 'その他')
#### インテリア・住まい・小物-ベッド/マットレス
interia_bed_grand = interia_bed.children.create(name: 'セミシングルベッド')
interia_bed_grand = interia_bed.children.create(name: 'シングルベッド')
interia_bed_grand = interia_bed.children.create(name: 'セミダブルベッド')
interia_bed_grand = interia_bed.children.create(name: 'ダブルベッド')
interia_bed_grand = interia_bed.children.create(name: 'ワイドダブルベッド')
interia_bed_grand = interia_bed.children.create(name: 'クイーンベッド')
interia_bed_grand = interia_bed.children.create(name: 'キングベッド')
interia_bed_grand = interia_bed.children.create(name: '脚付きマットレスベッド')
interia_bed_grand = interia_bed.children.create(name: 'マットレス')
interia_bed_grand = interia_bed.children.create(name: 'すのこベッド')
interia_bed_grand = interia_bed.children.create(name: 'ロフトベッド/システムベッド')
interia_bed_grand = interia_bed.children.create(name: '簡易ベッド/折りたたみベッド')
interia_bed_grand = interia_bed.children.create(name: '収納付き')
interia_bed_grand = interia_bed.children.create(name: 'その他')
#### インテリア・住まい・小物-ソファ/ソファベッド
interia_sofa_grand = interia_sofa.children.create(name: 'ソファセット')
interia_sofa_grand = interia_sofa.children.create(name: 'シングルソファ')
interia_sofa_grand = interia_sofa.children.create(name: 'ラブソファ')
interia_sofa_grand = interia_sofa.children.create(name: 'トリプルソファ')
interia_sofa_grand = interia_sofa.children.create(name: 'オットマン')
interia_sofa_grand = interia_sofa.children.create(name: 'コーナーソファ')
interia_sofa_grand = interia_sofa.children.create(name: 'ビーズソファ/クッションソファ')
interia_sofa_grand = interia_sofa.children.create(name: 'ローソファ/フロアソファ')
interia_sofa_grand = interia_sofa.children.create(name: 'ソファベッド')
interia_sofa_grand = interia_sofa.children.create(name: '応接セット')
interia_sofa_grand = interia_sofa.children.create(name: 'ソファカバー')
interia_sofa_grand = interia_sofa.children.create(name: 'リクライニングソファ')
interia_sofa_grand = interia_sofa.children.create(name: 'その他')
#### インテリア・住まい・小物-椅子/チェア
interia_chair_grand = interia_chair.children.create(name: '一般')
interia_chair_grand = interia_chair.children.create(name: 'スツール')
interia_chair_grand = interia_chair.children.create(name: 'ダイニングチェア')
interia_chair_grand = interia_chair.children.create(name: 'ハイバックチェア')
interia_chair_grand = interia_chair.children.create(name: 'ロッキングチェア')
interia_chair_grand = interia_chair.children.create(name: '座椅子')
interia_chair_grand = interia_chair.children.create(name: '折り畳みイス')
interia_chair_grand = interia_chair.children.create(name: 'デスクチェア')
interia_chair_grand = interia_chair.children.create(name: 'その他')
#### インテリア・住まい・小物-机/テーブル
interia_desk_grand = interia_desk.children.create(name: 'こたつ')
interia_desk_grand = interia_desk.children.create(name: 'カウンターテーブル')
interia_desk_grand = interia_desk.children.create(name: 'サイドテーブル')
interia_desk_grand = interia_desk.children.create(name: 'センターテーブル')
interia_desk_grand = interia_desk.children.create(name: 'ダイニングテーブル')
interia_desk_grand = interia_desk.children.create(name: '座卓/ちゃぶ台')
interia_desk_grand = interia_desk.children.create(name: 'アウトドア用')
interia_desk_grand = interia_desk.children.create(name: 'パソコン用')
interia_desk_grand = interia_desk.children.create(name: '事務机/学習机')
interia_desk_grand = interia_desk.children.create(name: 'その他')
#### インテリア・住まい・小物-収納家具
interia_kagu_grand = interia_kagu.children.create(name: 'リビング収納')
interia_kagu_grand = interia_kagu.children.create(name: 'キッチン収納')
interia_kagu_grand = interia_kagu.children.create(name: '玄関/屋外収納')
interia_kagu_grand = interia_kagu.children.create(name: 'バス/トイレ収納')
interia_kagu_grand = interia_kagu.children.create(name: '本収納')
interia_kagu_grand = interia_kagu.children.create(name: '本/CD/DVD収納')
interia_kagu_grand = interia_kagu.children.create(name: '洋服タンス/押入れ収納')
interia_kagu_grand = interia_kagu.children.create(name: '電話台/ファックス台')
interia_kagu_grand = interia_kagu.children.create(name: 'ドレッサー/鏡台')
interia_kagu_grand = interia_kagu.children.create(name: '棚/ラック')
interia_kagu_grand = interia_kagu.children.create(name: 'ケース/ボックス')
interia_kagu_grand = interia_kagu.children.create(name: 'その他')
#### インテリア・住まい・小物-ラグ/カーペット/マット
interia_carpet_grand = interia_carpet.children.create(name: 'ラグ')
interia_carpet_grand = interia_carpet.children.create(name: 'カーペット')
interia_carpet_grand = interia_carpet.children.create(name: 'ホットカーペット')
interia_carpet_grand = interia_carpet.children.create(name: '玄関/キッチンマット')
interia_carpet_grand = interia_carpet.children.create(name: 'トイレ/バスマット')
interia_carpet_grand = interia_carpet.children.create(name: 'その他')
#### インテリア・住まい・小物-カーテン/ブラインド
interia_kirten_grand = interia_kirten.children.create(name: 'カーテン')
interia_kirten_grand = interia_kirten.children.create(name: 'ブラインド')
interia_kirten_grand = interia_kirten.children.create(name: 'ロールスクリーン')
interia_kirten_grand = interia_kirten.children.create(name: 'のれん')
interia_kirten_grand = interia_kirten.children.create(name: 'その他')
#### インテリア・住まい・小物-ライト/照明
interia_light_grand = interia_light.children.create(name: '蛍光灯/電球')
interia_light_grand = interia_light.children.create(name: '天井照明')
interia_light_grand = interia_light.children.create(name: 'フロアスタンド')
interia_light_grand = interia_light.children.create(name: 'その他')
#### インテリア・住まい・小物-寝具
interia_singu_grand = interia_singu.children.create(name: '布団/毛布')
interia_singu_grand = interia_singu.children.create(name: '枕')
interia_singu_grand = interia_singu.children.create(name: 'シーツ/カバー')
interia_singu_grand = interia_singu.children.create(name: 'その他')
#### インテリア・住まい・小物-インテリア小物
interia_komono_grand = interia_komono.children.create(name: 'ごみ箱')
interia_komono_grand = interia_komono.children.create(name: 'ウェルカムボード')
interia_komono_grand = interia_komono.children.create(name: 'オルゴール')
interia_komono_grand = interia_komono.children.create(name: 'クッション')
interia_komono_grand = interia_komono.children.create(name: 'クッションカバー')
interia_komono_grand = interia_komono.children.create(name: 'スリッパラック')
interia_komono_grand = interia_komono.children.create(name: 'ティッシュボックス')
interia_komono_grand = interia_komono.children.create(name: 'バスケット/かご')
interia_komono_grand = interia_komono.children.create(name: 'フォトフレーム')
interia_komono_grand = interia_komono.children.create(name: 'マガジンラック')
interia_komono_grand = interia_komono.children.create(name: 'モビール')
interia_komono_grand = interia_komono.children.create(name: '花瓶')
interia_komono_grand = interia_komono.children.create(name: '灰皿')
interia_komono_grand = interia_komono.children.create(name: '傘立て')
interia_komono_grand = interia_komono.children.create(name: '小物入れ')
interia_komono_grand = interia_komono.children.create(name: '置時計')
interia_komono_grand = interia_komono.children.create(name: '掛時計/柱時計')
interia_komono_grand = interia_komono.children.create(name: '鏡(立て掛け式)')
interia_komono_grand = interia_komono.children.create(name: '鏡(壁掛け式)')
interia_komono_grand = interia_komono.children.create(name: '置物')
interia_komono_grand = interia_komono.children.create(name: '風鈴')
interia_komono_grand = interia_komono.children.create(name: '植物/観葉植物')
interia_komono_grand = interia_komono.children.create(name: 'その他')
#### インテリア・住まい・小物-季節/年中行事
interia_season_grand = interia_season.children.create(name: '正月')
interia_season_grand = interia_season.children.create(name: '成人式')
interia_season_grand = interia_season.children.create(name: 'バレンタインデー')
interia_season_grand = interia_season.children.create(name: 'ひな祭り')
interia_season_grand = interia_season.children.create(name: '子どもの日')
interia_season_grand = interia_season.children.create(name: '母の日')
interia_season_grand = interia_season.children.create(name: '父の日')
interia_season_grand = interia_season.children.create(name: 'サマーギフト/お中元')
interia_season_grand = interia_season.children.create(name: '夏/夏休み')
interia_season_grand = interia_season.children.create(name: 'ハロウィン')
interia_season_grand = interia_season.children.create(name: '敬老の日')
interia_season_grand = interia_season.children.create(name: '七五三')
interia_season_grand = interia_season.children.create(name: 'お歳暮')
interia_season_grand = interia_season.children.create(name: 'クリスマス')
interia_season_grand = interia_season.children.create(name: '冬一般')
interia_season_grand = interia_season.children.create(name: 'その他')
#### インテリア・住まい・小物-その他
#### 本・音楽・ゲーム-本
books_book_grand = books_book.children.create(name: '文学/小説')
books_book_grand = books_book.children.create(name: '人文/社会')
books_book_grand = books_book.children.create(name: 'ノンフィクション/教養')
books_book_grand = books_book.children.create(name: '地図/旅行ガイド')
books_book_grand = books_book.children.create(name: 'ビジネス/経済')
books_book_grand = books_book.children.create(name: '健康/医学')
books_book_grand = books_book.children.create(name: 'コンピュータ/IT')
books_book_grand = books_book.children.create(name: '趣味/スポーツ/実用')
books_book_grand = books_book.children.create(name: '住まい/暮らし/子育て')
books_book_grand = books_book.children.create(name: 'アート/エンタメ')
books_book_grand = books_book.children.create(name: '洋書')
books_book_grand = books_book.children.create(name: '絵本')
books_book_grand = books_book.children.create(name: '参考書')
books_book_grand = books_book.children.create(name: 'その他')
#### 本・音楽・ゲーム-漫画
books_manga_grand = books_manga.children.create(name: '全巻セット')
books_manga_grand = books_manga.children.create(name: '少年漫画')
books_manga_grand = books_manga.children.create(name: '少女漫画')
books_manga_grand = books_manga.children.create(name: '青年漫画')
books_manga_grand = books_manga.children.create(name: '女性漫画')
books_manga_grand = books_manga.children.create(name: '同人誌')
books_manga_grand = books_manga.children.create(name: 'その他')
#### 本・音楽・ゲーム-雑誌
books_magazine_grand = books_magazine.children.create(name: 'アート/エンタメ/ホビー')
books_magazine_grand = books_magazine.children.create(name: 'ファッション')
books_magazine_grand = books_magazine.children.create(name: 'ニュース/総合')
books_magazine_grand = books_magazine.children.create(name: '趣味/スポーツ')
books_magazine_grand = books_magazine.children.create(name: 'その他')
#### 本・音楽・ゲーム-CD
books_cd_grand = books_cd.children.create(name: '邦楽')
books_cd_grand = books_cd.children.create(name: '洋楽')
books_cd_grand = books_cd.children.create(name: 'アニメ')
books_cd_grand = books_cd.children.create(name: 'クラシック')
books_cd_grand = books_cd.children.create(name: 'K-POP/アジア')
books_cd_grand = books_cd.children.create(name: 'キッズ/ファミリー')
books_cd_grand = books_cd.children.create(name: 'その他')
#### 本・音楽・ゲーム-DVD/ブルーレイ
books_dvd_grand = books_dvd.children.create(name: '外国映画')
books_dvd_grand = books_dvd.children.create(name: '日本映画')
books_dvd_grand = books_dvd.children.create(name: 'アニメ')
books_dvd_grand = books_dvd.children.create(name: 'TVドラマ')
books_dvd_grand = books_dvd.children.create(name: 'ミュージック')
books_dvd_grand = books_dvd.children.create(name: 'お笑い/バラエティ')
books_dvd_grand = books_dvd.children.create(name: 'スポーツ/フィットネス')
books_dvd_grand = books_dvd.children.create(name: 'キッズ/ファミリー')
books_dvd_grand = books_dvd.children.create(name: 'その他')
#### 本・音楽・ゲーム-レコード
books_record_grand = books_record.children.create(name: '邦楽')
books_record_grand = books_record.children.create(name: '洋楽')
books_record_grand = books_record.children.create(name: 'その他')
#### 本・音楽・ゲーム-テレビゲーム
books_game_grand = books_game.children.create(name: '家庭用ゲーム本体')
books_game_grand = books_game.children.create(name: '家庭用ゲームソフト')
books_game_grand = books_game.children.create(name: '携帯用ゲーム本体')
books_game_grand = books_game.children.create(name: '携帯用ゲームソフト')
books_game_grand = books_game.children.create(name: 'PCゲーム')
books_game_grand = books_game.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-おもちゃ
hobby_toy_grand = hobby_toy.children.create(name: 'キャラクターグッズ')
hobby_toy_grand = hobby_toy.children.create(name: 'ぬいぐるみ')
hobby_toy_grand = hobby_toy.children.create(name: '小物/アクセサリー')
hobby_toy_grand = hobby_toy.children.create(name: '模型/プラモデル')
hobby_toy_grand = hobby_toy.children.create(name: 'ミニカー')
hobby_toy_grand = hobby_toy.children.create(name: 'トイラジコン')
hobby_toy_grand = hobby_toy.children.create(name: 'プラモデル')
hobby_toy_grand = hobby_toy.children.create(name: 'ホビーラジコン')
hobby_toy_grand = hobby_toy.children.create(name: '鉄道模型')
hobby_toy_grand = hobby_toy.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-タレントグッズ
hobby_talent_grand = hobby_talent.children.create(name: 'アイドル')
hobby_talent_grand = hobby_talent.children.create(name: 'ミュージシャン')
hobby_talent_grand = hobby_talent.children.create(name: 'タレント/お笑い芸人')
hobby_talent_grand = hobby_talent.children.create(name: 'スポーツ選手')
hobby_talent_grand = hobby_talent.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-コミック/アニメグッズ
hobby_comic_grand = hobby_comic.children.create(name: 'ストラップ')
hobby_comic_grand = hobby_comic.children.create(name: 'キーホルダー')
hobby_comic_grand = hobby_comic.children.create(name: 'バッジ')
hobby_comic_grand = hobby_comic.children.create(name: 'カード')
hobby_comic_grand = hobby_comic.children.create(name: 'クリアファイル')
hobby_comic_grand = hobby_comic.children.create(name: 'ポスター')
hobby_comic_grand = hobby_comic.children.create(name: 'タオル')
hobby_comic_grand = hobby_comic.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-トレーディングカード
hobby_card_grand = hobby_card.children.create(name: '遊戯王')
hobby_card_grand = hobby_card.children.create(name: 'マジック：ザ・ギャザリング')
hobby_card_grand = hobby_card.children.create(name: 'ポケモンカードゲーム')
hobby_card_grand = hobby_card.children.create(name: 'デュエルマスターズ')
hobby_card_grand = hobby_card.children.create(name: 'バトルスピリッツ')
hobby_card_grand = hobby_card.children.create(name: 'プリパラ')
hobby_card_grand = hobby_card.children.create(name: 'アイカツ')
hobby_card_grand = hobby_card.children.create(name: 'カードファイト!! ヴァンガード')
hobby_card_grand = hobby_card.children.create(name: 'ヴァイスシュヴァルツ')
hobby_card_grand = hobby_card.children.create(name: 'プロ野球オーナーズリーグ')
hobby_card_grand = hobby_card.children.create(name: 'ベースボールヒーローズ')
hobby_card_grand = hobby_card.children.create(name: 'ドラゴンボール')
hobby_card_grand = hobby_card.children.create(name: 'スリーブ')
hobby_card_grand = hobby_card.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-フィギュア
hobby_figma_grand = hobby_figma.children.create(name: 'コミック/アニメ')
hobby_figma_grand = hobby_figma.children.create(name: '特撮')
hobby_figma_grand = hobby_figma.children.create(name: 'ゲームキャラクター')
hobby_figma_grand = hobby_figma.children.create(name: 'SF/ファンタジー/ホラー')
hobby_figma_grand = hobby_figma.children.create(name: 'アメコミ')
hobby_figma_grand = hobby_figma.children.create(name: 'スポーツ')
hobby_figma_grand = hobby_figma.children.create(name: 'ミリタリー')
hobby_figma_grand = hobby_figma.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-楽器/器材
hobby_gakki_grand = hobby_gakki.children.create(name: 'エレキギター')
hobby_gakki_grand = hobby_gakki.children.create(name: 'アコースティックギター')
hobby_gakki_grand = hobby_gakki.children.create(name: 'ベース')
hobby_gakki_grand = hobby_gakki.children.create(name: 'エフェクター')
hobby_gakki_grand = hobby_gakki.children.create(name: 'アンプ')
hobby_gakki_grand = hobby_gakki.children.create(name: '弦楽器')
hobby_gakki_grand = hobby_gakki.children.create(name: '管楽器')
hobby_gakki_grand = hobby_gakki.children.create(name: '鍵盤楽器')
hobby_gakki_grand = hobby_gakki.children.create(name: '打楽器')
hobby_gakki_grand = hobby_gakki.children.create(name: '和楽器')
hobby_gakki_grand = hobby_gakki.children.create(name: '楽譜/スコア')
hobby_gakki_grand = hobby_gakki.children.create(name: 'レコーディング/PA機器')
hobby_gakki_grand = hobby_gakki.children.create(name: 'DJ機器')
hobby_gakki_grand = hobby_gakki.children.create(name: 'DTM/DAW')
hobby_gakki_grand = hobby_gakki.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-コレクション
hobby_collection_grand = hobby_collection.children.create(name: '武具')
hobby_collection_grand = hobby_collection.children.create(name: '使用済切手/官製はがき')
hobby_collection_grand = hobby_collection.children.create(name: '旧貨幣/金貨/銀貨/記念硬貨')
hobby_collection_grand = hobby_collection.children.create(name: '印刷物')
hobby_collection_grand = hobby_collection.children.create(name: 'ノベルティグッズ')
hobby_collection_grand = hobby_collection.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-ミリタリー
hobby_military_grand = hobby_military.children.create(name: 'トイガン')
hobby_military_grand = hobby_military.children.create(name: '個人装備')
hobby_military_grand = hobby_military.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-美術品
hobby_art_grand = hobby_art.children.create(name: '陶芸')
hobby_art_grand = hobby_art.children.create(name: 'ガラス')
hobby_art_grand = hobby_art.children.create(name: '漆芸')
hobby_art_grand = hobby_art.children.create(name: '金属工芸')
hobby_art_grand = hobby_art.children.create(name: '絵画/タペストリ')
hobby_art_grand = hobby_art.children.create(name: '版画')
hobby_art_grand = hobby_art.children.create(name: '彫刻/オブジェクト')
hobby_art_grand = hobby_art.children.create(name: '書')
hobby_art_grand = hobby_art.children.create(name: '写真')
hobby_art_grand = hobby_art.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-アート用品
hobby_arting_grand = hobby_arting.children.create(name: '画材')
hobby_arting_grand = hobby_arting.children.create(name: '額縁')
hobby_arting_grand = hobby_arting.children.create(name: 'その他')
#### おもちゃ・ホビー・グッズ-その他
hobby_others_grand = hobby_others.children.create(name: 'トランプ/UNO')
hobby_others_grand = hobby_others.children.create(name: 'カルタ/百人一首')
hobby_others_grand = hobby_others.children.create(name: 'ダーツ')
hobby_others_grand = hobby_others.children.create(name: 'ビリヤード')
hobby_others_grand = hobby_others.children.create(name: '麻雀')
hobby_others_grand = hobby_others.children.create(name: 'パズル/ジグソーパズル')
hobby_others_grand = hobby_others.children.create(name: '囲碁/将棋')
hobby_others_grand = hobby_others.children.create(name: 'オセロ/チェス')
hobby_others_grand = hobby_others.children.create(name: '人生ゲーム')
hobby_others_grand = hobby_others.children.create(name: '野球/サッカーゲーム')
hobby_others_grand = hobby_others.children.create(name: 'スポーツ')
hobby_others_grand = hobby_others.children.create(name: '三輪車/乗り物')
hobby_others_grand = hobby_others.children.create(name: 'ヨーヨー')
hobby_others_grand = hobby_others.children.create(name: '模型製作用品')
hobby_others_grand = hobby_others.children.create(name: '鉄道')
hobby_others_grand = hobby_others.children.create(name: '航空機')
hobby_others_grand = hobby_others.children.create(name: 'アマチュア無線')
hobby_others_grand = hobby_others.children.create(name: 'パチンコ/パチスロ')
hobby_others_grand = hobby_others.children.create(name: 'その他')
#### コスメ・香水・美容-ベースメイク
cosme_base_grand = cosme_base.children.create(name: 'ファンデーション')
cosme_base_grand = cosme_base.children.create(name: '化粧下地')
cosme_base_grand = cosme_base.children.create(name: 'コントロールカラー')
cosme_base_grand = cosme_base.children.create(name: 'BBクリーム')
cosme_base_grand = cosme_base.children.create(name: 'CCクリーム')
cosme_base_grand = cosme_base.children.create(name: 'コンシーラー')
cosme_base_grand = cosme_base.children.create(name: 'フェイスパウダー')
cosme_base_grand = cosme_base.children.create(name: 'トライアルセット/サンプル')
cosme_base_grand = cosme_base.children.create(name: 'その他')
#### コスメ・香水・美容-メイクアップ
cosme_makeup_grand = cosme_makeup.children.create(name: 'アイシャドウ')
cosme_makeup_grand = cosme_makeup.children.create(name: '口紅')
cosme_makeup_grand = cosme_makeup.children.create(name: 'リップグロス')
cosme_makeup_grand = cosme_makeup.children.create(name: 'リップライナー')
cosme_makeup_grand = cosme_makeup.children.create(name: 'チーク')
cosme_makeup_grand = cosme_makeup.children.create(name: 'フェイスカラー')
cosme_makeup_grand = cosme_makeup.children.create(name: 'マスカラ')
cosme_makeup_grand = cosme_makeup.children.create(name: 'アイライナー')
cosme_makeup_grand = cosme_makeup.children.create(name: 'つけまつげ')
cosme_makeup_grand = cosme_makeup.children.create(name: 'アイブロウペンシル')
cosme_makeup_grand = cosme_makeup.children.create(name: 'パウダーアイブロウ')
cosme_makeup_grand = cosme_makeup.children.create(name: '眉マスカラ')
cosme_makeup_grand = cosme_makeup.children.create(name: 'トライアルセット/サンプル')
cosme_makeup_grand = cosme_makeup.children.create(name: 'メイク道具/化粧小物')
cosme_makeup_grand = cosme_makeup.children.create(name: '美顔用品/美顔ローラー')
cosme_makeup_grand = cosme_makeup.children.create(name: 'その他')
#### コスメ・香水・美容-ネイルケア
cosme_nail_grand = cosme_nail.children.create(name: 'ネイルカラー')
cosme_nail_grand = cosme_nail.children.create(name: 'カラージェル')
cosme_nail_grand = cosme_nail.children.create(name: 'ネイルベースコート/トップコート')
cosme_nail_grand = cosme_nail.children.create(name: 'ネイルアート用品')
cosme_nail_grand = cosme_nail.children.create(name: 'ネイルパーツ')
cosme_nail_grand = cosme_nail.children.create(name: 'ネイルチップ/付け爪')
cosme_nail_grand = cosme_nail.children.create(name: '手入れ用具')
cosme_nail_grand = cosme_nail.children.create(name: '除光液')
cosme_nail_grand = cosme_nail.children.create(name: 'その他')
#### コスメ・香水・美容-香水
cosme_kosui_grand = cosme_kosui.children.create(name: '香水(女性用)')
cosme_kosui_grand = cosme_kosui.children.create(name: '香水(男性用)')
cosme_kosui_grand = cosme_kosui.children.create(name: 'ユニセックス')
cosme_kosui_grand = cosme_kosui.children.create(name: 'ボディミスト')
cosme_kosui_grand = cosme_kosui.children.create(name: 'その他')
#### コスメ・香水・美容-スキンケア/基礎化粧品
cosme_skin_grand = cosme_skin.children.create(name: '化粧水/ローション')
cosme_skin_grand = cosme_skin.children.create(name: '乳液/ミルク')
cosme_skin_grand = cosme_skin.children.create(name: '美容液')
cosme_skin_grand = cosme_skin.children.create(name: 'フェイスクリーム')
cosme_skin_grand = cosme_skin.children.create(name: '洗顔料')
cosme_skin_grand = cosme_skin.children.create(name: 'クレンジング/メイク落とし')
cosme_skin_grand = cosme_skin.children.create(name: 'パック/フェイスマスク')
cosme_skin_grand = cosme_skin.children.create(name: 'ジェル/ゲル')
cosme_skin_grand = cosme_skin.children.create(name: 'ブースター/導入液')
cosme_skin_grand = cosme_skin.children.create(name: 'アイケア')
cosme_skin_grand = cosme_skin.children.create(name: 'リップケア')
cosme_skin_grand = cosme_skin.children.create(name: 'トライアルセット/サンプル')
cosme_skin_grand = cosme_skin.children.create(name: '洗顔グッズ')
cosme_skin_grand = cosme_skin.children.create(name: 'その他')
#### コスメ・香水・美容-ヘアケア
cosme_hair_grand = cosme_hair.children.create(name: 'シャンプー')
cosme_hair_grand = cosme_hair.children.create(name: 'トリートメント')
cosme_hair_grand = cosme_hair.children.create(name: 'コンディショナー')
cosme_hair_grand = cosme_hair.children.create(name: 'リンス')
cosme_hair_grand = cosme_hair.children.create(name: 'スタイリング剤')
cosme_hair_grand = cosme_hair.children.create(name: 'カラーリング剤')
cosme_hair_grand = cosme_hair.children.create(name: 'ブラシ')
cosme_hair_grand = cosme_hair.children.create(name: 'その他')
#### コスメ・香水・美容-ボディケア
cosme_body_grand = cosme_body.children.create(name: 'オイル/クリーム')
cosme_body_grand = cosme_body.children.create(name: 'ハンドクリーム')
cosme_body_grand = cosme_body.children.create(name: 'ローション')
cosme_body_grand = cosme_body.children.create(name: '日焼け止め/サンオイル')
cosme_body_grand = cosme_body.children.create(name: 'ボディソープ')
cosme_body_grand = cosme_body.children.create(name: '入浴剤')
cosme_body_grand = cosme_body.children.create(name: '制汗/デオドラント')
cosme_body_grand = cosme_body.children.create(name: 'フットケア')
cosme_body_grand = cosme_body.children.create(name: 'その他')
#### コスメ・香水・美容-オーラルケア
cosme_oral_grand = cosme_oral.children.create(name: '口臭防止/エチケット用品')
cosme_oral_grand = cosme_oral.children.create(name: '歯ブラシ')
cosme_oral_grand = cosme_oral.children.create(name: 'その他')
#### コスメ・香水・美容-リラクゼーション
cosme_relax_grand = cosme_relax.children.create(name: 'エッセンシャルオイル')
cosme_relax_grand = cosme_relax.children.create(name: '芳香器')
cosme_relax_grand = cosme_relax.children.create(name: 'お香/香炉')
cosme_relax_grand = cosme_relax.children.create(name: 'キャンドル')
cosme_relax_grand = cosme_relax.children.create(name: 'リラクゼーショングッズ')
cosme_relax_grand = cosme_relax.children.create(name: 'その他')
#### コスメ・香水・美容-ダイエット
cosme_diet_grand = cosme_diet.children.create(name: 'ダイエット食品')
cosme_diet_grand = cosme_diet.children.create(name: 'エクササイズ用品')
cosme_diet_grand = cosme_diet.children.create(name: '体重計')
cosme_diet_grand = cosme_diet.children.create(name: '体脂肪計')
cosme_diet_grand = cosme_diet.children.create(name: 'その他')
#### コスメ・香水・美容-その他
cosme_others_grand = cosme_others.children.create(name: '健康用品')
cosme_others_grand = cosme_others.children.create(name: '看護/介護用品')
cosme_others_grand = cosme_others.children.create(name: '救急/衛生用品')
cosme_others_grand = cosme_others.children.create(name: 'その他')
#### 家電・スマホ・カメラ-スマートフォン/携帯電話
cameras_phone_grand = cameras_phone.children.create(name: 'スマートフォン本体')
cameras_phone_grand = cameras_phone.children.create(name: 'バッテリー/充電器')
cameras_phone_grand = cameras_phone.children.create(name: '携帯電話本体')
cameras_phone_grand = cameras_phone.children.create(name: 'PHS本体')
cameras_phone_grand = cameras_phone.children.create(name: 'その他')
#### 家電・スマホ・カメラ-スマホアクセサリー
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: 'Android用ケース')
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: 'iPhone用ケース')
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: 'カバー')
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: 'イヤホンジャック')
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: 'ストラップ')
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: 'フィルム')
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: '自撮り棒')
cameras_phoneAccessary_grand = cameras_phoneAccessary.children.create(name: 'その他')
#### 家電・スマホ・カメラ-PC/タブレット
cameras_pc_grand = cameras_pc.children.create(name: 'タブレット')
cameras_pc_grand = cameras_pc.children.create(name: 'ノートPC')
cameras_pc_grand = cameras_pc.children.create(name: 'デスクトップ型PC')
cameras_pc_grand = cameras_pc.children.create(name: 'ディスプレイ')
cameras_pc_grand = cameras_pc.children.create(name: '電子ブックリーダー')
cameras_pc_grand = cameras_pc.children.create(name: 'PC周辺機器')
cameras_pc_grand = cameras_pc.children.create(name: 'PCパーツ')
cameras_pc_grand = cameras_pc.children.create(name: 'その他')
#### 家電・スマホ・カメラ-カメラ
cameras_camera_grand = cameras_camera.children.create(name: 'デジタルカメラ')
cameras_camera_grand = cameras_camera.children.create(name: 'ビデオカメラ')
cameras_camera_grand = cameras_camera.children.create(name: 'レンズ(単焦点)')
cameras_camera_grand = cameras_camera.children.create(name: 'レンズ(ズーム)')
cameras_camera_grand = cameras_camera.children.create(name: 'フィルムカメラ')
cameras_camera_grand = cameras_camera.children.create(name: '防犯カメラ')
cameras_camera_grand = cameras_camera.children.create(name: 'その他')
#### 家電・スマホ・カメラ-テレビ/映像機器
cameras_televi_grand = cameras_televi.children.create(name: 'テレビ')
cameras_televi_grand = cameras_televi.children.create(name: 'プロジェクター')
cameras_televi_grand = cameras_televi.children.create(name: 'ブルーレイレコーダー')
cameras_televi_grand = cameras_televi.children.create(name: 'DVDレコーダー')
cameras_televi_grand = cameras_televi.children.create(name: 'ブルーレイプレーヤー')
cameras_televi_grand = cameras_televi.children.create(name: 'DVDプレーヤー')
cameras_televi_grand = cameras_televi.children.create(name: '映像用ケーブル')
cameras_televi_grand = cameras_televi.children.create(name: 'その他')
#### 家電・スマホ・カメラ-オーディオ機器
cameras_audio_grand = cameras_audio.children.create(name: 'ポータブルプレーヤー')
cameras_audio_grand = cameras_audio.children.create(name: 'イヤフォン')
cameras_audio_grand = cameras_audio.children.create(name: 'ヘッドフォン')
cameras_audio_grand = cameras_audio.children.create(name: 'アンプ')
cameras_audio_grand = cameras_audio.children.create(name: 'スピーカー')
cameras_audio_grand = cameras_audio.children.create(name: 'ケーブル/シールド')
cameras_audio_grand = cameras_audio.children.create(name: 'ラジオ')
cameras_audio_grand = cameras_audio.children.create(name: 'その他')
#### 家電・スマホ・カメラ-美容/健康
cameras_biyou_grand = cameras_biyou.children.create(name: 'ヘアドライヤー')
cameras_biyou_grand = cameras_biyou.children.create(name: 'ヘアアイロン')
cameras_biyou_grand = cameras_biyou.children.create(name: '美容機器')
cameras_biyou_grand = cameras_biyou.children.create(name: '電気シェーバー')
cameras_biyou_grand = cameras_biyou.children.create(name: '電動歯ブラシ')
cameras_biyou_grand = cameras_biyou.children.create(name: 'その他')
#### 家電・スマホ・カメラ-冷暖房/空調
cameras_reibou_grand = cameras_reibou.children.create(name: 'エアコン')
cameras_reibou_grand = cameras_reibou.children.create(name: '空気清浄器')
cameras_reibou_grand = cameras_reibou.children.create(name: '加湿器')
cameras_reibou_grand = cameras_reibou.children.create(name: '扇風機')
cameras_reibou_grand = cameras_reibou.children.create(name: '除湿機')
cameras_reibou_grand = cameras_reibou.children.create(name: 'ファンヒーター')
cameras_reibou_grand = cameras_reibou.children.create(name: '電気ヒーター')
cameras_reibou_grand = cameras_reibou.children.create(name: 'オイルヒーター')
cameras_reibou_grand = cameras_reibou.children.create(name: 'ストーブ')
cameras_reibou_grand = cameras_reibou.children.create(name: 'ホットカーペット')
cameras_reibou_grand = cameras_reibou.children.create(name: 'こたつ')
cameras_reibou_grand = cameras_reibou.children.create(name: '電気毛布')
cameras_reibou_grand = cameras_reibou.children.create(name: 'その他')
#### 家電・スマホ・カメラ-生活家電
cameras_kaden_grand = cameras_kaden.children.create(name: '冷蔵庫')
cameras_kaden_grand = cameras_kaden.children.create(name: '洗濯機')
cameras_kaden_grand = cameras_kaden.children.create(name: '炊飯器')
cameras_kaden_grand = cameras_kaden.children.create(name: '電子レンジ/オーブン')
cameras_kaden_grand = cameras_kaden.children.create(name: '調理機器')
cameras_kaden_grand = cameras_kaden.children.create(name: 'アイロン')
cameras_kaden_grand = cameras_kaden.children.create(name: '掃除機')
cameras_kaden_grand = cameras_kaden.children.create(name: 'エスプレッソマシン')
cameras_kaden_grand = cameras_kaden.children.create(name: 'コーヒーメーカー')
cameras_kaden_grand = cameras_kaden.children.create(name: '衣類乾燥機')
cameras_kaden_grand = cameras_kaden.children.create(name: 'その他')
#### 家電・スマホ・カメラ-その他
cameras_others_grand = cameras_others.children.create(name: 'その他')
#### スポーツ・レジャー-ゴルフ
sport_golf_grand = sport_golf.children.create(name: 'クラブ')
sport_golf_grand = sport_golf.children.create(name: 'ウエア(男性用)')
sport_golf_grand = sport_golf.children.create(name: 'ウエア(女性用)')
sport_golf_grand = sport_golf.children.create(name: 'バッグ')
sport_golf_grand = sport_golf.children.create(name: 'シューズ(男性用)')
sport_golf_grand = sport_golf.children.create(name: 'シューズ(女性用)')
sport_golf_grand = sport_golf.children.create(name: 'アクセサリー')
sport_golf_grand = sport_golf.children.create(name: 'その他')
#### スポーツ・レジャー-フィッシング
sport_fishing_grand = sport_fishing.children.create(name: 'ロッド')
sport_fishing_grand = sport_fishing.children.create(name: 'リール')
sport_fishing_grand = sport_fishing.children.create(name: 'ルアー用品')
sport_fishing_grand = sport_fishing.children.create(name: 'ウエア')
sport_fishing_grand = sport_fishing.children.create(name: '釣り糸/ライン')
sport_fishing_grand = sport_fishing.children.create(name: 'その他')
#### スポーツ・レジャー-自転車
sport_bike_grand = sport_bike.children.create(name: '自転車本体')
sport_bike_grand = sport_bike.children.create(name: 'ウエア')
sport_bike_grand = sport_bike.children.create(name: 'パーツ')
sport_bike_grand = sport_bike.children.create(name: 'アクセサリー')
sport_bike_grand = sport_bike.children.create(name: 'バッグ')
sport_bike_grand = sport_bike.children.create(name: '工具/メンテナンス')
sport_bike_grand = sport_bike.children.create(name: 'その他')
#### スポーツ・レジャー-トレーニング/エクササイズ
sport_training_grand = sport_training.children.create(name: 'ランニング')
sport_training_grand = sport_training.children.create(name: 'ウォーキング')
sport_training_grand = sport_training.children.create(name: 'ヨガ')
sport_training_grand = sport_training.children.create(name: 'トレーニング用品')
sport_training_grand = sport_training.children.create(name: 'その他')
#### スポーツ・レジャー-野球
sport_baseball_grand = sport_baseball.children.create(name: 'ウェア')
sport_baseball_grand = sport_baseball.children.create(name: 'シューズ')
sport_baseball_grand = sport_baseball.children.create(name: 'グローブ')
sport_baseball_grand = sport_baseball.children.create(name: 'バット')
sport_baseball_grand = sport_baseball.children.create(name: 'アクセサリー')
sport_baseball_grand = sport_baseball.children.create(name: '防具')
sport_baseball_grand = sport_baseball.children.create(name: '練習機器')
sport_baseball_grand = sport_baseball.children.create(name: '記念グッズ')
sport_baseball_grand = sport_baseball.children.create(name: '応援グッズ')
sport_baseball_grand = sport_baseball.children.create(name: 'その他')
#### スポーツ・レジャー-サッカー/フットサル
sport_soccer_grand = sport_soccer.children.create(name: 'ウェア')
sport_soccer_grand = sport_soccer.children.create(name: 'シューズ')
sport_soccer_grand = sport_soccer.children.create(name: 'ボール')
sport_soccer_grand = sport_soccer.children.create(name: 'アクセサリー')
sport_soccer_grand = sport_soccer.children.create(name: '記念グッズ')
sport_soccer_grand = sport_soccer.children.create(name: '応援グッズ')
sport_soccer_grand = sport_soccer.children.create(name: 'その他')
#### スポーツ・レジャー-テニス
sport_tennis_grand = sport_tennis.children.create(name: 'ラケット(硬式用)')
sport_tennis_grand = sport_tennis.children.create(name: 'ラケット(軟式用)')
sport_tennis_grand = sport_tennis.children.create(name: 'ウェア')
sport_tennis_grand = sport_tennis.children.create(name: 'シューズ')
sport_tennis_grand = sport_tennis.children.create(name: 'ボール')
sport_tennis_grand = sport_tennis.children.create(name: 'アクセサリー')
sport_tennis_grand = sport_tennis.children.create(name: '記念グッズ')
sport_tennis_grand = sport_tennis.children.create(name: '応援グッズ')
sport_tennis_grand = sport_tennis.children.create(name: 'その他')
#### スポーツ・レジャー-スノーボード
sport_snow_grand = sport_snow.children.create(name: 'ボード')
sport_snow_grand = sport_snow.children.create(name: 'バインディング')
sport_snow_grand = sport_snow.children.create(name: 'ブーツ(男性用)')
sport_snow_grand = sport_snow.children.create(name: 'ブーツ(女性用)')
sport_snow_grand = sport_snow.children.create(name: 'ブーツ(子ども用)')
sport_snow_grand = sport_snow.children.create(name: 'ウエア/装備(男性用)')
sport_snow_grand = sport_snow.children.create(name: 'ウエア/装備(女性用)')
sport_snow_grand = sport_snow.children.create(name: 'ウエア/装備(子ども用)')
sport_snow_grand = sport_snow.children.create(name: 'アクセサリー')
sport_snow_grand = sport_snow.children.create(name: 'バッグ')
sport_snow_grand = sport_snow.children.create(name: 'その他')
#### スポーツ・レジャー-スキー
sport_skii_grand = sport_skii.children.create(name: '板')
sport_skii_grand = sport_skii.children.create(name: 'ブーツ(男性用)')
sport_skii_grand = sport_skii.children.create(name: 'ブーツ(女性用)')
sport_skii_grand = sport_skii.children.create(name: 'ブーツ(子ども用)')
sport_skii_grand = sport_skii.children.create(name: 'ビンディング')
sport_skii_grand = sport_skii.children.create(name: 'ウエア(男性用)')
sport_skii_grand = sport_skii.children.create(name: 'ウエア(女性用)')
sport_skii_grand = sport_skii.children.create(name: 'ウエア(子ども用)')
sport_skii_grand = sport_skii.children.create(name: 'ストック')
sport_skii_grand = sport_skii.children.create(name: 'その他')
#### スポーツ・レジャー-その他スポーツ
sport_otherSports_grand = sport_otherSports.children.create(name: 'ダンス/バレエ')
sport_otherSports_grand = sport_otherSports.children.create(name: 'サーフィン')
sport_otherSports_grand = sport_otherSports.children.create(name: 'バスケットボール')
sport_otherSports_grand = sport_otherSports.children.create(name: 'バドミントン')
sport_otherSports_grand = sport_otherSports.children.create(name: 'バレーボール')
sport_otherSports_grand = sport_otherSports.children.create(name: 'スケートボード')
sport_otherSports_grand = sport_otherSports.children.create(name: '陸上競技')
sport_otherSports_grand = sport_otherSports.children.create(name: 'ラグビー')
sport_otherSports_grand = sport_otherSports.children.create(name: 'アメリカンフットボール')
sport_otherSports_grand = sport_otherSports.children.create(name: 'ボクシング')
sport_otherSports_grand = sport_otherSports.children.create(name: 'ボウリング')
sport_otherSports_grand = sport_otherSports.children.create(name: 'その他')
#### スポーツ・レジャー-アウトドア
sport_outdoor_grand = sport_outdoor.children.create(name: 'テント/タープ')
sport_outdoor_grand = sport_outdoor.children.create(name: 'ライト/ランタン')
sport_outdoor_grand = sport_outdoor.children.create(name: '寝袋/寝具')
sport_outdoor_grand = sport_outdoor.children.create(name: 'テーブル/チェア')
sport_outdoor_grand = sport_outdoor.children.create(name: 'ストーブ/コンロ')
sport_outdoor_grand = sport_outdoor.children.create(name: '調理器具')
sport_outdoor_grand = sport_outdoor.children.create(name: '食器')
sport_outdoor_grand = sport_outdoor.children.create(name: '登山用品')
sport_outdoor_grand = sport_outdoor.children.create(name: 'その他')
#### スポーツ・レジャー-その他
sport_others_grand = sport_others.children.create(name: '旅行用品')
sport_others_grand = sport_others.children.create(name: 'その他')
#### ハンドメイド-アクセサリー(女性用)
hands_accessary_grand = hands_accessary.children.create(name: 'ピアス')
hands_accessary_grand = hands_accessary.children.create(name: 'イヤリング')
hands_accessary_grand = hands_accessary.children.create(name: 'ネックレス')
hands_accessary_grand = hands_accessary.children.create(name: 'ブレスレット')
hands_accessary_grand = hands_accessary.children.create(name: 'リング')
hands_accessary_grand = hands_accessary.children.create(name: 'チャーム')
hands_accessary_grand = hands_accessary.children.create(name: 'ヘアゴム')
hands_accessary_grand = hands_accessary.children.create(name: 'アンクレット')
hands_accessary_grand = hands_accessary.children.create(name: 'その他')
#### ハンドメイド-ファッション/小物
hands_fashion_grand = hands_fashion.children.create(name: 'バッグ(女性用)')
hands_fashion_grand = hands_fashion.children.create(name: 'バッグ(男性用)')
hands_fashion_grand = hands_fashion.children.create(name: '財布(女性用)')
hands_fashion_grand = hands_fashion.children.create(name: '財布(男性用)')
hands_fashion_grand = hands_fashion.children.create(name: 'ファッション雑貨')
hands_fashion_grand = hands_fashion.children.create(name: 'その他')
#### ハンドメイド-アクセサリー/時計
hands_clock_grand = hands_clock.children.create(name: 'アクセサリー(男性用)')
hands_clock_grand = hands_clock.children.create(name: '時計(女性用)')
hands_clock_grand = hands_clock.children.create(name: '時計(男性用)')
hands_clock_grand = hands_clock.children.create(name: 'その他')
#### ハンドメイド-日用品/インテリア
hands_interia_grand = hands_interia.children.create(name: 'キッチン用品')
hands_interia_grand = hands_interia.children.create(name: '家具')
hands_interia_grand = hands_interia.children.create(name: '文房具')
hands_interia_grand = hands_interia.children.create(name: 'アート/写真')
hands_interia_grand = hands_interia.children.create(name: 'アロマ/キャンドル')
hands_interia_grand = hands_interia.children.create(name: 'フラワー/ガーデン')
hands_interia_grand = hands_interia.children.create(name: 'その他')
#### ハンドメイド-趣味/おもちゃ
hands_hobby_grand = hands_hobby.children.create(name: 'クラフト/布製品')
hands_hobby_grand = hands_hobby.children.create(name: 'おもちゃ/人形')
hands_hobby_grand = hands_hobby.children.create(name: 'その他')
#### ハンドメイド-キッズ/ベビー
hands_kids_grand = hands_kids.children.create(name: 'ファッション雑貨')
hands_kids_grand = hands_kids.children.create(name: 'スタイ/よだれかけ')
hands_kids_grand = hands_kids.children.create(name: '外出用品')
hands_kids_grand = hands_kids.children.create(name: 'ネームタグ')
hands_kids_grand = hands_kids.children.create(name: 'その他')
#### ハンドメイド-素材/材料
hands_material_grand = hands_material.children.create(name: '各種パーツ')
hands_material_grand = hands_material.children.create(name: '生地/糸')
hands_material_grand = hands_material.children.create(name: '型紙/パターン')
hands_material_grand = hands_material.children.create(name: 'その他')
#### ハンドメイド-二次創作物
hands_dojin_grand = hands_dojin.children.create(name: 'Ingress')
hands_dojin_grand = hands_dojin.children.create(name: 'クリエイターズ宇宙兄弟')
#### ハンドメイド-その他
#### チケット-音楽
tickets_music_grand = tickets_music.children.create(name: '男性アイドル')
tickets_music_grand = tickets_music.children.create(name: '女性アイドル')
tickets_music_grand = tickets_music.children.create(name: '韓流')
tickets_music_grand = tickets_music.children.create(name: '国内アーティスト')
tickets_music_grand = tickets_music.children.create(name: '海外アーティスト')
tickets_music_grand = tickets_music.children.create(name: '音楽フェス')
tickets_music_grand = tickets_music.children.create(name: '声優/アニメ')
tickets_music_grand = tickets_music.children.create(name: 'その他')
#### チケット-スポーツ
tickets_sports_grand = tickets_sports.children.create(name: 'サッカー')
tickets_sports_grand = tickets_sports.children.create(name: '野球')
tickets_sports_grand = tickets_sports.children.create(name: 'テニス')
tickets_sports_grand = tickets_sports.children.create(name: '格闘技/プロレス')
tickets_sports_grand = tickets_sports.children.create(name: '相撲/武道')
tickets_sports_grand = tickets_sports.children.create(name: 'ゴルフ')
tickets_sports_grand = tickets_sports.children.create(name: 'バレーボール')
tickets_sports_grand = tickets_sports.children.create(name: 'バスケットボール')
tickets_sports_grand = tickets_sports.children.create(name: 'モータースポーツ')
tickets_sports_grand = tickets_sports.children.create(name: 'ウィンタースポーツ')
tickets_sports_grand = tickets_sports.children.create(name: 'その他')
#### チケット-演劇/芸能
tickets_engeki_grand = tickets_engeki.children.create(name: 'ミュージカル')
tickets_engeki_grand = tickets_engeki.children.create(name: '演劇')
tickets_engeki_grand = tickets_engeki.children.create(name: '伝統芸能')
tickets_engeki_grand = tickets_engeki.children.create(name: '落語')
tickets_engeki_grand = tickets_engeki.children.create(name: 'お笑い')
tickets_engeki_grand = tickets_engeki.children.create(name: 'オペラ')
tickets_engeki_grand = tickets_engeki.children.create(name: 'サーカス')
tickets_engeki_grand = tickets_engeki.children.create(name: 'バレエ')
tickets_engeki_grand = tickets_engeki.children.create(name: 'その他')
#### チケット-イベント
tickets_event_grand = tickets_event.children.create(name: '声優/アニメ')
tickets_event_grand = tickets_event.children.create(name: 'キッズ/ファミリー')
tickets_event_grand = tickets_event.children.create(name: 'トークショー/講演会')
tickets_event_grand = tickets_event.children.create(name: 'その他')
#### チケット-映画
tickets_movie_grand = tickets_movie.children.create(name: '邦画')
tickets_movie_grand = tickets_movie.children.create(name: '洋画')
tickets_movie_grand = tickets_movie.children.create(name: 'その他')
#### チケット-施設利用券
tickets_shisetu_grand = tickets_shisetu.children.create(name: '遊園地/テーマパーク')
tickets_shisetu_grand = tickets_shisetu.children.create(name: '美術館/博物館')
tickets_shisetu_grand = tickets_shisetu.children.create(name: 'スキー場')
tickets_shisetu_grand = tickets_shisetu.children.create(name: 'ゴルフ場')
tickets_shisetu_grand = tickets_shisetu.children.create(name: 'フィットネスクラブ')
tickets_shisetu_grand = tickets_shisetu.children.create(name: 'プール')
tickets_shisetu_grand = tickets_shisetu.children.create(name: 'ボウリング場')
tickets_shisetu_grand = tickets_shisetu.children.create(name: '水族館')
tickets_shisetu_grand = tickets_shisetu.children.create(name: '動物園')
tickets_shisetu_grand = tickets_shisetu.children.create(name: 'その他')
#### チケット-優待券/割引券
tickets_yuutai_grand = tickets_yuutai.children.create(name: 'ショッピング')
tickets_yuutai_grand = tickets_yuutai.children.create(name: 'レストラン/食事券')
tickets_yuutai_grand = tickets_yuutai.children.create(name: 'フード/ドリンク券')
tickets_yuutai_grand = tickets_yuutai.children.create(name: '宿泊券')
tickets_yuutai_grand = tickets_yuutai.children.create(name: 'その他')
#### チケット-その他
#### 自動車・オートバイ-自動車本体
cars_bike_grand = cars_bike.children.create(name: '国内自動車本体')
cars_bike_grand = cars_bike.children.create(name: '外国自動車本体')
#### 自動車・オートバイ-自動車タイヤ/ホイール
cars_hoile_grand = cars_hoile.children.create(name: 'タイヤ/ホイールセット')
cars_hoile_grand = cars_hoile.children.create(name: 'タイヤ')
cars_hoile_grand = cars_hoile.children.create(name: 'ホイール')
cars_hoile_grand = cars_hoile.children.create(name: 'その他')
#### 自動車・オートバイ-自動車パーツ
cars_wheel_grand = cars_wheel.children.create(name: 'サスペンション')
cars_wheel_grand = cars_wheel.children.create(name: 'ブレーキ')
cars_wheel_grand = cars_wheel.children.create(name: '外装、エアロパーツ')
cars_wheel_grand = cars_wheel.children.create(name: 'ライト')
cars_wheel_grand = cars_wheel.children.create(name: '内装品、シート')
cars_wheel_grand = cars_wheel.children.create(name: 'ステアリング')
cars_wheel_grand = cars_wheel.children.create(name: 'マフラー・排気系')
cars_wheel_grand = cars_wheel.children.create(name: 'エンジン、過給器、冷却装置')
cars_wheel_grand = cars_wheel.children.create(name: 'クラッチ、ミッション、駆動系')
cars_wheel_grand = cars_wheel.children.create(name: '電装品')
cars_wheel_grand = cars_wheel.children.create(name: '補強パーツ')
cars_wheel_grand = cars_wheel.children.create(name: '汎用パーツ')
cars_wheel_grand = cars_wheel.children.create(name: '外国自動車用パーツ')
cars_wheel_grand = cars_wheel.children.create(name: 'その他')
#### 自動車・オートバイ-自動車アクセサリー
cars_accessary_grand = cars_accessary.children.create(name: '車内アクセサリー')
cars_accessary_grand = cars_accessary.children.create(name: 'カーナビ')
cars_accessary_grand = cars_accessary.children.create(name: 'カーオーディオ')
cars_accessary_grand = cars_accessary.children.create(name: '車外アクセサリー')
cars_accessary_grand = cars_accessary.children.create(name: 'メンテナンス用品')
cars_accessary_grand = cars_accessary.children.create(name: 'チャイルドシート')
cars_accessary_grand = cars_accessary.children.create(name: 'ドライブレコーダー')
cars_accessary_grand = cars_accessary.children.create(name: 'レーダー探知機')
cars_accessary_grand = cars_accessary.children.create(name: 'カタログ/マニュアル')
cars_accessary_grand = cars_accessary.children.create(name: 'セキュリティ')
cars_accessary_grand = cars_accessary.children.create(name: 'ETC')
cars_accessary_grand = cars_accessary.children.create(name: 'その他')
#### 自動車・オートバイ-オートバイ車体
#### 自動車・オートバイ-オートバイパーツ
cars_parts_grand = cars_parts.children.create(name: 'タイヤ')
cars_parts_grand = cars_parts.children.create(name: 'マフラー')
cars_parts_grand = cars_parts.children.create(name: 'エンジン、冷却装置')
cars_parts_grand = cars_parts.children.create(name: 'カウル、フェンダー、外装')
cars_parts_grand = cars_parts.children.create(name: 'サスペンション')
cars_parts_grand = cars_parts.children.create(name: 'ホイール')
cars_parts_grand = cars_parts.children.create(name: 'シート')
cars_parts_grand = cars_parts.children.create(name: 'ブレーキ')
cars_parts_grand = cars_parts.children.create(name: 'タンク')
cars_parts_grand = cars_parts.children.create(name: 'ライト、ウィンカー')
cars_parts_grand = cars_parts.children.create(name: 'チェーン、スプロケット、駆動系')
cars_parts_grand = cars_parts.children.create(name: 'メーター')
cars_parts_grand = cars_parts.children.create(name: '電装系')
cars_parts_grand = cars_parts.children.create(name: 'ミラー')
cars_parts_grand = cars_parts.children.create(name: '外国オートバイ用パーツ')
cars_parts_grand = cars_parts.children.create(name: 'その他')
#### 自動車・オートバイ-オートバイアクセサリー
cars_autobikeAccessary_grand = cars_autobikeAccessary.children.create(name: 'ヘルメット/シールド')
cars_autobikeAccessary_grand = cars_autobikeAccessary.children.create(name: 'バイクウエア/装備')
cars_autobikeAccessary_grand = cars_autobikeAccessary.children.create(name: 'アクセサリー')
cars_autobikeAccessary_grand = cars_autobikeAccessary.children.create(name: 'メンテナンス')
cars_autobikeAccessary_grand = cars_autobikeAccessary.children.create(name: 'カタログ/マニュアル')
cars_autobikeAccessary_grand = cars_autobikeAccessary.children.create(name: 'その他')
#### その他-まとめ売り
#### その他-ペット用品
others_pet_grand = others_pet.children.create(name: 'ペットフード')
others_pet_grand = others_pet.children.create(name: '犬用品')
others_pet_grand = others_pet.children.create(name: '猫用品')
others_pet_grand = others_pet.children.create(name: '魚用品/水草')
others_pet_grand = others_pet.children.create(name: '小動物用品')
others_pet_grand = others_pet.children.create(name: '爬虫類/両生類用品')
others_pet_grand = others_pet.children.create(name: 'かご/おり')
others_pet_grand = others_pet.children.create(name: '鳥用品')
others_pet_grand = others_pet.children.create(name: '虫類用品')
others_pet_grand = others_pet.children.create(name: 'その他')
#### その他-食品
others_foods_grand = others_foods.children.create(name: '菓子')
others_foods_grand = others_foods.children.create(name: '米')
others_foods_grand = others_foods.children.create(name: '野菜')
others_foods_grand = others_foods.children.create(name: '果物')
others_foods_grand = others_foods.children.create(name: '調味料')
others_foods_grand = others_foods.children.create(name: '魚介類(加工食品)')
others_foods_grand = others_foods.children.create(name: '肉類(加工食品)')
others_foods_grand = others_foods.children.create(name: 'その他 加工食品')
others_foods_grand = others_foods.children.create(name: 'その他')
#### その他-飲料/酒
others_sake_grand = others_sake.children.create(name: 'コーヒー')
others_sake_grand = others_sake.children.create(name: 'ソフトドリンク')
others_sake_grand = others_sake.children.create(name: 'ミネラルウォーター')
others_sake_grand = others_sake.children.create(name: '茶')
others_sake_grand = others_sake.children.create(name: 'ウイスキー')
others_sake_grand = others_sake.children.create(name: 'ワイン')
others_sake_grand = others_sake.children.create(name: 'ブランデー')
others_sake_grand = others_sake.children.create(name: '焼酎')
others_sake_grand = others_sake.children.create(name: '日本酒')
others_sake_grand = others_sake.children.create(name: 'ビール、発泡酒')
others_sake_grand = others_sake.children.create(name: 'その他')
#### その他-日用品/生活雑貨/旅行
others_zakka_grand = others_zakka.children.create(name: 'タオル/バス用品')
others_zakka_grand = others_zakka.children.create(name: '日用品/生活雑貨')
others_zakka_grand = others_zakka.children.create(name: '洗剤/柔軟剤')
others_zakka_grand = others_zakka.children.create(name: '旅行用品')
others_zakka_grand = others_zakka.children.create(name: '防災関連グッズ')
others_zakka_grand = others_zakka.children.create(name: 'その他')
#### その他-アンティーク/コレクション
others_antike_grand = others_antike.children.create(name: '雑貨')
others_antike_grand = others_antike.children.create(name: '工芸品')
others_antike_grand = others_antike.children.create(name: '家具')
others_antike_grand = others_antike.children.create(name: '印刷物')
others_antike_grand = others_antike.children.create(name: 'その他')
#### その他-文房具/事務用品
others_bunbogu_grand = others_bunbogu.children.create(name: '筆記具')
others_bunbogu_grand = others_bunbogu.children.create(name: 'ノート/メモ帳')
others_bunbogu_grand = others_bunbogu.children.create(name: 'テープ/マスキングテープ')
others_bunbogu_grand = others_bunbogu.children.create(name: 'カレンダー/スケジュール')
others_bunbogu_grand = others_bunbogu.children.create(name: 'アルバム/スクラップ')
others_bunbogu_grand = others_bunbogu.children.create(name: 'ファイル/バインダー')
others_bunbogu_grand = others_bunbogu.children.create(name: 'はさみ/カッター')
others_bunbogu_grand = others_bunbogu.children.create(name: 'カードホルダー/名刺管理')
others_bunbogu_grand = others_bunbogu.children.create(name: 'のり/ホッチキス')
others_bunbogu_grand = others_bunbogu.children.create(name: 'その他')
#### その他-事務/店舗用品
others_jimu_grand = others_jimu.children.create(name: 'オフィス用品一般')
others_jimu_grand = others_jimu.children.create(name: 'オフィス家具')
others_jimu_grand = others_jimu.children.create(name: '店舗用品')
others_jimu_grand = others_jimu.children.create(name: 'OA機器')
others_jimu_grand = others_jimu.children.create(name: 'ラッピング/包装')
others_jimu_grand = others_jimu.children.create(name: 'その他')