# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Categoryモデル
## 親カテゴリー
category = Category.create(name: 'すべて')
default = category.children.create(name: '選択してください')
ladys = category.children.create(name: 'レディース')
mens = category.children.create(name: 'メンズ')
babys = category.children.create(name: 'ベビー・キッズ')
interia = category.children.create(name: 'インテリア・住まい・小物')
books = category.children.create(name: '本・音楽・ゲーム')
hobby = category.children.create(name: 'おもちゃ・ホビー・グッズ')
cosme = category.children.create(name: 'コスメ・香水・美容')
cameras = category.children.create(name: '家電・スマホ・カメラ')
sport = category.children.create(name: 'スポーツ・レジャー')
hands = category.children.create(name: 'ハンドメイド')
tickets = category.children.create(name: 'チケット')
cars = category.children.create(name: '自動車・オートバイ')
others = category.children.create(name: 'その他')

## 子カテゴリー
### レディース
ladys_tops = ladys.children.create(name: 'トップス')
ladys_jaket = ladys.children.create(name: 'ジャケット/アウター')
ladys_pant = ladys.children.create(name: 'パンツ')
ladys_skirt = ladys.children.create(name: 'スカート')
ladys_wanpi = ladys.children.create(name: 'ワンピース')
ladys_shoes = ladys.children.create(name: '靴')
ladys_room = ladys.children.create(name: 'ルームウェア/パジャマ')
ladys_leg = ladys.children.create(name: 'レッグウェア')
ladys_hat = ladys.children.create(name: '帽子')
ladys_bag = ladys.children.create(name: 'バッグ')
ladys_accessary = ladys.children.create(name: 'アクセサリー')
ladys_hair = ladys.children.create(name: 'ヘアアクセサリー')
ladys_komono = ladys.children.create(name: '小物')
ladys_clock = ladys.children.create(name: '時計')
ladys_wig = ladys.children.create(name: 'ウィッグ/エクステ')
ladys_yukata = ladys.children.create(name: '浴衣/水着')
ladys_suutu = ladys.children.create(name: 'スーツ/フォーマル/ドレス')
ladys_matanity = ladys.children.create(name: 'マタニティ')
ladys_others = ladys.children.create(name: 'その他')
# ### メンズ
# mens_tops = mens.children.create(name: 'トップス')
# mens_jaket = mens.children.create(name: 'ジャケット/アウター')
# mens_pant = mens.children.create(name: 'パンツ')
# mens_shoes = mens.children.create(name: '靴')
# mens_bag = mens.children.create(name: 'バッグ')
# mens_suutu = mens.children.create(name: 'スーツ')
# mens_hat = mens.children.create(name: '帽子')
# mens_accessary = mens.children.create(name: 'アクセサリー')
# mens_komono = mens.children.create(name: '小物')
# mens_clock = mens.children.create(name: '時計')
# mens_mizugi = mens.children.create(name: '水着')
# mens_leg = mens.children.create(name: 'レッグウェア')
# mens_under = mens.children.create(name: 'アンダーウェア')
# mens_others = mens.children.create(name: 'その他')
# ### ベビー・キッズ
# babys_girl95 = babys.children.create(name: 'ベビー服(女の子用) ~95cm')
# babys_boy95 = babys.children.create(name: 'ベビー服(男の子用) ~95cm')
# babys_both95 = babys.children.create(name: 'ベビー服(男女兼用) ~95cm')
# babys_girl100 = babys.children.create(name: 'キッズ服(女の子用) 100cm~')
# babys_boy100 = babys.children.create(name: 'キッズ服(男の子用) 100cm~')
# babys_both100 = babys.children.create(name: 'キッズ服(男女兼用) 100cm~')
# babys_shoes = babys.children.create(name: 'キッズ靴')
# babys_fashion = babys.children.create(name: '子ども用ファッション小物')
# babys_omutsu = babys.children.create(name: 'おむつ/トイレ/バス')
# babys_move = babys.children.create(name: '外出/移動用具')
# babys_lunch = babys.children.create(name: '授乳/食事')
# babys_kagu = babys.children.create(name: 'ベビー家具/寝具/室内用品')
# babys_toy = babys.children.create(name: 'おもちゃ')
# babys_event = babys.children.create(name: '行事/記念品')
# babys_others = babys.children.create(name: 'その他')
# ### インテリア
# interia_kitchen = interia.children.create(name: 'キッチン/食器')
# interia_bed = interia.children.create(name: 'ベッド/マットレス')
# interia_sofa = interia.children.create(name: 'ソファ/ソファベッド')
# interia_chair = interia.children.create(name: '椅子/チェア')
# interia_desk = interia.children.create(name: '机/テーブル')
# interia_kagu = interia.children.create(name: '収納家具')
# interia_carpet = interia.children.create(name: 'ラグ/カーペット/マット')
# interia_kirten = interia.children.create(name: 'カーテン/ブラインド')
# interia_light = interia.children.create(name: 'ライト/照明')
# interia_singu = interia.children.create(name: '寝具')
# interia_komono = interia.children.create(name: 'インテリア小物')
# interia_season = interia.children.create(name: '季節/年中行事')
# interia_others = interia.children.create(name: 'その他')
# ### 本
# books_book = books.children.create(name: '本')
# books_manga = books.children.create(name: '漫画')
# books_magazine = books.children.create(name: '雑誌')
# books_cd = books.children.create(name: 'CD')
# books_dvd = books.children.create(name: 'DVD/ブルーレイ')
# books_record = books.children.create(name: 'レコード')
# books_game = books.children.create(name: 'テレビゲーム')
# ### おもちゃ
# hobby_toy = hobby.children.create(name: 'おもちゃ')
# hobby_talent = hobby.children.create(name: 'タレントグッズ')
# hobby_comic = hobby.children.create(name: 'コミック/アニメグッズ')
# hobby_card = hobby.children.create(name: 'トレーディングカード')
# hobby_figma = hobby.children.create(name: 'フィギュア')
# hobby_gakki = hobby.children.create(name: '楽器/器材')
# hobby_collection = hobby.children.create(name: 'コレクション')
# hobby_military = hobby.children.create(name: 'ミリタリー')
# hobby_art = hobby.children.create(name: '美術品')
# hobby_arting = hobby.children.create(name: 'アート用品')
# hobby_others = hobby.children.create(name: 'その他')
# ### コスメ
# cosme_base = cosme.children.create(name: 'ベースメイク')
# cosme_makeup = cosme.children.create(name: 'メイクアップ')
# cosme_nail = cosme.children.create(name: 'ネイルケア')
# cosme_kosui = cosme.children.create(name: '香水')
# cosme_skin = cosme.children.create(name: 'スキンケア/基礎化粧品')
# cosme_hair = cosme.children.create(name: 'ヘアケア')
# cosme_body = cosme.children.create(name: 'ボディケア')
# cosme_oral = cosme.children.create(name: 'オーラルケア')
# cosme_relax = cosme.children.create(name: 'リラクゼーション')
# cosme_diet = cosme.children.create(name: 'ダイエット')
# cosme_others = cosme.children.create(name: 'その他')
# ### 家電・スマホ・カメラ
# cameras_phone = cameras.children.create(name: 'スマートフォン/携帯電話')
# cameras_phoneAccessary = cameras.children.create(name: 'スマホアクセサリー')
# cameras_pc = cameras.children.create(name: 'PC/タブレット')
# cameras_camera = cameras.children.create(name: 'カメラ')
# cameras_televi = cameras.children.create(name: 'テレビ/映像機器')
# cameras_audio = cameras.children.create(name: 'オーディオ機器')
# cameras_biyou = cameras.children.create(name: '美容/健康')
# cameras_reibou = cameras.children.create(name: '冷暖房/空調')
# cameras_kaden = cameras.children.create(name: '生活家電')
# cameras_others = cameras.children.create(name: 'その他')
# ### スポーツ・レジャー
# sport_golf = sport.children.create(name: 'ゴルフ')
# sport_fishing = sport.children.create(name: 'フィッシング')
# sport_bike = sport.children.create(name: '自転車')
# sport_training = sport.children.create(name: 'トレーニング/エクササイズ')
# sport_baseball = sport.children.create(name: '野球')
# sport_soccer = sport.children.create(name: 'サッカー/フットサル')
# sport_tennis = sport.children.create(name: 'テニス')
# sport_snow = sport.children.create(name: 'スノーボード')
# sport_skii = sport.children.create(name: 'スキー')
# sport_otherSports = sport.children.create(name: 'その他スポーツ')
# sport_outdoor = sport.children.create(name: 'アウトドア')
# sport_others = sport.children.create(name: 'その他')
# ### ハンドメイド
# hands_accessary = hands.children.create(name: 'アクセサリー(女性用)')
# hands_fashion = hands.children.create(name: 'ファッション/小物')
# hands_clock = hands.children.create(name: 'アクセサリー/時計')
# hands_interia = hands.children.create(name: '日用品/インテリア')
# hands_hobby = hands.children.create(name: '趣味/おもちゃ')
# hands_kids = hands.children.create(name: 'キッズ/ベビー')
# hands_material = hands.children.create(name: '素材/材料')
# hands_dojin = hands.children.create(name: '二次創作物')
# hands_others = hands.children.create(name: 'その他')
# ### チケット
# tickets_music = tickets.children.create(name: '音楽')
# tickets_sports = tickets.children.create(name: 'スポーツ')
# tickets_engeki = tickets.children.create(name: '演劇/芸能')
# tickets_event = tickets.children.create(name: 'イベント')
# tickets_movie = tickets.children.create(name: '映画')
# tickets_shisetu = tickets.children.create(name: '施設利用券')
# tickets_yuutai = tickets.children.create(name: '優待券/割引券')
# tickets_others = tickets.children.create(name: 'その他')
# ### 自転車・オートバイ
# cars_bike = cars.children.create(name: '自動車本体')
# cars_hoile = cars.children.create(name: '自動車タイヤ/ホイール')
# cars_wheel = cars.children.create(name: '自動車パーツ')
# cars_accessary = cars.children.create(name: '自動車アクセサリー')
# cars_autobike = cars.children.create(name: 'オートバイ車体')
# cars_parts = cars.children.create(name: 'オートバイパーツ')
# cars_autobikeAccessary = cars.children.create(name: 'オートバイアクセサリー')
# ### その他
# others_matome = others.children.create(name: 'まとめ売り')
# others_pet = others.children.create(name: 'ペット用品')
# others_foods = others.children.create(name: '食品')
# others_sake = others.children.create(name: '食料/酒')
# others_zakka = others.children.create(name: '日用品/生活雑貨/旅行')
# others_antike = others.children.create(name: 'アンティーク/コレクション')
# others_bunbogu = others.children.create(name: '文房具/事務用品')
# others_jimu = others.children.create(name: '事務/店舗用品')
# others_others = others.children.create(name: 'その他')

## 孫カテゴリー
### レディース
#### トップス
ladys_tops_grand = ladys_tops.children.create(name: 'Tシャツ/カットソー(半袖/袖なし)')
ladys_tops_grand = ladys_tops.children.create(name: 'Tシャツ/カットソー(七分/長袖)')
ladys_tops_grand = ladys_tops.children.create(name: 'シャツ/ブラウス(半袖/袖なし)')
ladys_tops_grand = ladys_tops.children.create(name: 'シャツ/ブラウス(七分/長袖)')
ladys_tops_grand = ladys_tops.children.create(name: 'ポロシャツ')
ladys_tops_grand = ladys_tops.children.create(name: 'タンクトップ')
ladys_tops_grand = ladys_tops.children.create(name: 'ホルターネック')
ladys_tops_grand = ladys_tops.children.create(name: 'ニット/セーター')
ladys_tops_grand = ladys_tops.children.create(name: 'チュニック')
ladys_tops_grand = ladys_tops.children.create(name: 'カーディガン/ボレロ')
ladys_tops_grand = ladys_tops.children.create(name: 'アンサンブル')
ladys_tops_grand = ladys_tops.children.create(name: 'ベスト/ジレ')
ladys_tops_grand = ladys_tops.children.create(name: 'パーカー')
ladys_tops_grand = ladys_tops.children.create(name: 'トレーナー/スウェット')
ladys_tops_grand = ladys_tops.children.create(name: 'ベアトップ/チューブトップ')
ladys_tops_grand = ladys_tops.children.create(name: 'ジャージ')
ladys_tops_grand = ladys_tops.children.create(name: 'その他')


